### ISSUE TITLE
Unknown limits for link flair.. bug

### ISSUE THREAD

**Issue by anonimeco** [voat/voat#112]
http://whoaverse.com/v/whoaversedev/comments/23838

_Ad verbatium;_

> I've spotted this a few days ago, but only now remembered to report it.
> 
> When creating link flairs, I apparently am limited to 20 link flairs despite there being no warning of it, when I try to add a new one it completely ignores it or at least it doesn't display them (if that is the case, I might have a few couple of invisible flairs).
> 
> And when I try applying a link flair to a submission, I can only select "Clear Current Flair" or one of the first 10 link flairs that exist.

Don't know what else to write considering you know what the issue is.

**Comment by vskjefst** [comment]
I'm experiencing the same issue. If I edit the JS-call on the button used to add a specific flair to a submission with the ID of a flair I've added to the subverse that's not showing up in the list, I'm able to add the "hidden" flair to the submission. It's just not being displayed in the list of available flairs...

**Comment by jrupp** [comment]
Browsed through the code, the problem appears to be here: [Voat/Voat.UI/Controllers/AjaxGatewayController.cs:97](https://github.com/voat/voat/blob/a5f7479e922ff711553bc631c48780bbe1b8318e/Voat/Voat.UI/Controllers/AjaxGatewayController.cs#L97)

The `.Take(10)` is limiting the returned results to 10 when selecting flair.  Since only moderators can do this, we should probably just remove the limit at all.. let it load all the flair.. an if that turns out to be a problem, then someone will need to write something to paginate the results

Also, the limit of 20 on the edit page is here:
[Voat/Voat.UI/Controllers/SubversesController.cs:1403](https://github.com/voat/voat/blob/60eebcb71bbbfe755cb9ab7318028f3501b66e14/Voat/Voat.UI/Controllers/SubversesController.cs#L1403)

I can go make a pull request to have this removed.

**Comment by PuttItOut** [comment]
Should be fixed.

**Comment by MagicalBlob** [comment]
Still only 20 flairs displayed in the flair management page and only 10 in the flair selection modal.

![image](https://cloud.githubusercontent.com/assets/6509486/19990121/1f3727a2-a223-11e6-8f70-bc7a5d200b92.png)
