### ISSUE TITLE
Sets layout

### ISSUE THREAD

**Issue by voat** [voat/voat#221]
Instead of frontpage being populated by content from default subs ordered by rank (thus having multiple submissions from a single sub while other, less active subs get less exposure), we should display the content in sets in a similar fashion of Google News - http://news.google.com/.

This feature should allow full user customization, allowing the user to add/remove subs from sets, add/remove sets or adjust the number of items in each set. Set page position should also be adjustable.

**Comment by moeVoat** [comment]
Is this feature still being prioritized / actively developed?

I really want to use the sets layout and promote it, but none of the buttons on the layout work for me (except for "edit" & "Subscribe"), and the "Subscribe" button is only visible on the list of sets next to each one but not on the individual sets' pages.

The latter issue is my main one since explaining to people that they need to find a new set in a list of ~200 in order to subscribe discourages them from doing so.

**Comment by PuttItOut** [comment]
Closed as sets needs to be entirely revisited.
