### ISSUE TITLE
User names can be longer than maximum length permissable for user name in contact form.

### ISSUE THREAD

**Issue by hellokevin11** [voat/voat#264]
Contacting a user with a 21 character nickname is impossible as there is a 20 character limit to the name in the contact page.

**Comment by DanielFlamino** [comment]
But there is a 20 character limit for the name on the account creation page? Can you give the name of a user with 21 characters? o_O

**Comment by voat** [comment]
As Daniel said, there is a 20 character limit on usernames but it is possible that some users registered their accounts before this limit was imposed. This is a bug and we'll need to do something about it. Thank you for reporting it.

**Comment by voat** [comment]
I found several user accounts with usernames >20 characters. They were all inactive and I deleted them. There were 2 active accounts with usernames consisting of 22 and 23 characters. In order to let other users send them messages, I modified the viewmodels to accept upto 23 characters. This should now work fine although new registrations will not be able to exceed 20 characters. Thank you for reporting this.
