### ISSUE TITLE
Deleting a stickied submission does not remove the sticky

### ISSUE THREAD

**Issue by voat** [voat/voat#297]
Deleting a stickied submission does not remove the sticky

**Comment by mgiuffrida** [comment]
Deleting a stickied submission still does not remove the sticky. In my case there have been some kind of race condition, as I think I (accidentally) stickied the post immediately before deleting it.

https://voat.co/v/sf

**Comment by mgiuffrida** [comment]
O_O Something strange just happened. The subverse had been in this state for > 1 day:

- [sticky] Deleted post
- My post

I just stickied my post, which result in:

- [sticky] My post
- My post

Then unstickied my post, resulting in just:

- My post

So [the original stickied deleted post](https://voat.co/v/SF/comments/144127) no longer shows up, as if its sticky slot was "masked" by the undeleted sticky. Feels like a dirty bit was triggered somewhere that should have been set initially but missed because of a cache or something.
