### ISSUE TITLE
merge start discussion and share a link into one view

### ISSUE THREAD

**Issue by voat** [voat/voat#331]
As described here: https://voat.co/v/ideasforvoat/comments/57906

**Comment by DanielFlamino** [comment]
I've just noticed that, with this, [an old suggestion that I did](https://voat.co/v/announcements/comments/11770/12365) will no longer be part of Voat. Oh well... ¯\\_(ツ)_/¯

**Comment by PuttItOut** [comment]
I'm designing the API to support this workflow btw so I'm assuming we all agree to merge the submission types into one?

**Comment by voat** [comment]
There is a huge number of places (at least 30 locations) where submission type is being checked for various things which would need refactoring. I say we stay with current workflow for now. Refactoring this would be a big pain.

On another note, if users submit a link with an accompanying message, this may be abused in a way. Imagine for example someone submitting a link to a news article and writing something completely unrelated, insulting etc. Many people upvote links without going to the comments (or in this case, reading the accompanying text) and the link may end up on the frontpage even though the people who upvoted it did not intend to (because they did not read the accompanying message).

**Comment by PuttItOut** [comment]
I think the scenario of users submitting a link and then having to comment on the post to provide context is a much more common scenario than someone writing something opinionated in it that doesn't match the link.

If you applied the same logic to post titles, you wouldn't even allow them for a link submission because titles can be abused in the same way you are claiming, not matching the link, unrelated, insulting, etc. 

I think the pros outweigh the cons on this one, but don't worry, the API can support both scenarios with small logic changes.

**Comment by voat** [comment]
There are more ways to abuse this. The way we have discussion type submissions functioning now, content could be edited after posting. This can be abused for example once a post reaches the frontpage and an unrelated spam link could be added by the user, to plug his website, a product on a webstore etc. To circumvent this, we would have to disable context editing for submissions which contain an url... All of this is way too much work for 1 visual change.
