### ISSUE TITLE
Replace EF with Dapper?

### ISSUE THREAD

**Issue by voat** [voat/voat#343]
We should look into this:
https://github.com/StackExchange/dapper-dot-net

**Comment by PuttItOut** [comment]
This scares me. Gutting EF at this stage would be an issue. A big one. And I'm pretty much anti-EF to begin with....

**Comment by artganify** [comment]
I really like Dapper, mostly because of it's incredible performance and stability. Also being more of a simple ORM than a full fledged data access framework, it doesn't enforce that many restrictions when it comes to designing entities, unlike e.g. EF.

@PuttItOut @voat You should really look into the different ways of abstracting frameworks and technologies away from your core domain, e.g. by introducing something like repository pattern for data access via clear and domain related interfaces, also use the power of an IoC to manage service dependencies (e.g. via dependency injection or interception (AOP)). That wouldn't change much of the functionality of your code, but would allow you to easily swap out infrastructure concerns, writing non-implementation depending unit tests for TDD/BDD style development etc. It's not the holy grail of everything, requires some deeper thinking about exact requirements of your platform.., but I strongly advise you to look into common architectural and design patterns like DDD (Domain Driven Design) and n-Layered-Architecture for further development.

**Comment by PuttItOut** [comment]
Yeah I agree 100%. If this was a funded project, we would do everything that should be done, but very hard to do with limited time and finances. Until then it's slow going and incremental changes.

**Comment by artganify** [comment]
@PuttItOut Agreed. Maybe I'll find some time at the weekend to look into the code to see what could be done easily without investing to much time. But when I last checked a few months ago, I noticed that a lot of entities were created in a model first approach: Refactoring them to true domain entities would heavily impact all other layers, so I don't have to much hope. ;) Anyway, keep up the good work - voat is already way more than just a reddit clone. ;)

**Comment by dodyg** [comment]
I think it is better to wait a bit and see what EF 7 brings. ASP.NET 5 is shaping up to be amazing and it should be straightforward to migrate to.

**Comment by artganify** [comment]
@dodyg While I think EF7 will be a totally new game, it still has the same flaws as EF6 (telling by whats already there in their repo): It tries to be something no one ever asked it to be. People working with ORMs are looking forward to abstract away the clumsy, provider-specific SQL stuff to deal with something much closer to what they already have in their domain. EF however is way more than just an ORM, it's a full fledged database framework capable of things like object tracking, lazy loading, migrations and connectivity management. While all these features are neat, they enforce very specific rules on the entities, thus degrading them to pure property pags. There are workarounds for many issues, but most of them clutter the code and add unnecessary complexity.

**Comment by artganify** [comment]
@dodyg For the new ASP.NET: Yes, migration of existing application logic will be very easy. But working with the platform itself won't be, if you're not familiar with all the cool toys of modern web development. Say, did you ever had to [*grunt*](http://i.imgur.com/hCGRSf9h.jpg) because some [*sass*y](http://i.imgur.com/fagE8Fe.jpg) [*bower*](http://i.imgur.com/55z2Wxel.jpg) pecked at the [*node*](http://i.imgur.com/gGxwFKZ.jpg)s of your [*jasmine*](http://i.imgur.com/CeCjqJn.jpg) plant? ;)

**Comment by dodyg** [comment]
We are essentially just putting in and out of the DB. There's a finite way to do that and they are actually boring work.

Migrations is actually quite useful because right now Voat doesn't have one. There's too much friction when there's a schema change (although I prefer fluentmigration). 

What aspnet 5 bring is simply much less memory usage (simply because it ditches system.web), cross platform, better deployment story and future investments to the platform.

So all things considered, it is much better to stick to EF6 for now to minimize migration path for ASP5, and decide on the ORM situation later. 

Another nice micro ORM is actually https://github.com/jonwagner/Insight.Database

**Comment by artganify** [comment]
@dodyg Insight looks really promising, I didn't know that one, so thank you. 

I think what OP was suggesting was switching to a micro ORM because of improved performance and reduced overhead, which I wholeheartedly agree upon because EF is indeed a clumsy brick and it's functionality feels like going on a duck hunt with a flak. But, as @PuttItOut already mentioned, the resources required to make a switch would be simply too big for a project like voat.

So instead of focusing on a certain technology, development should go towards abstraction and, regarding database, enforcing persistence ignorance. If voat establishes a strong domain and all functional requirements can be proven, deciding on a certain framework isn't a big deal anymore.

@dodyg As for migrations, fluentmigrator is indeed a nice tool. But this should also not be a big concern since it's the job of the application layer to establish a valid environment in which a domain can run in. :)

**Comment by dodyg** [comment]
EF7 will be faster. The question is how much faster. We shall wait and see. 

I think it is easy to agree that EF is a train wreck. My company uses LLBLGen instead but it is not suitable for open source development.

Database schema management IMHO is critical to make faster changes to the system. Right now when there is a new commit affecting the schema of the DB, there's no easy way to upgrade your development DB. I know because I have been through this while setting up a copy of whoaverse for a friend.

Anyway when I got free time to contribute again I will add FluentMigrator to this project so moving to a new schema wouldn't be such a PITA.

**Comment by jamesbascle** [comment]
I am using Dapper in production now. Dapper is GREAT.  It is extremely fast, and allows you to really cut out the clutter.  It also lets you write SQL in SQL, with some amazing helper syntax and methods to be quite productive.  Did I mention how fast it is?

I love me some LINQ, but I think it really just obfuscates the issue when dealing with SQL.  I think one thing EF is useful for is migrations though.

Dapper + the CQRS pattern is really powerful.  Siloing your data manipulation and your data access from one another also helps scale later on, since you can easily create readonly copies of your prod database, and treat your entire site as an event pipeline, where the flow looks like:

Website > Backend Server > Command Object > Dapper-backed Command Handler (can also push this object off to an eventhub/queue for your SignalR server to pickup and push out to clients in real time) > Master Database Write > Automatic Replication To Read-Only DBs < Dapper-backed Query Handler < Query Object < Backend Server < Website.

A site like Voat (like most sites) is inherently going to have a far bigger read requirement than write requirement.  This flow lets you scale each operation separately and have far fewer growing pains.  

EF is great for small stuff, especially internal LoB apps, but if you're going to operate at any kind of scale, you need to ditch it and pick up either Dapper or Peta-Poco or similar.  I suggest Dapper for the above mentioned reasons, and the significant fact that it is backed by StackOverflow and some of their great developers.

**Comment by dodyg** [comment]
Nice points overall (EF is a pretty terrible migrator - I suggest FluentMigrator) but the problem with Voat is not its architecture at the moment. The problem is that it is still starved of contributing developers. Until this gets fixed, reworking the architecture will be a foolish undertaking.

**Comment by voat** [comment]
Thank you all for discussing this. We'll stick with EF for a while.
