### ISSUE TITLE
[Feature Request] Add support for push notifications

### ISSUE THREAD

**Issue by quantumwannabe** [voat/voat#367]
Chrome recently released an api for allowing websites to send push notifications to users. The advantages of the new approach are that it works without the user currently having the page open, and it produces native notifications on mobile. Right now it uses GCM to communicate between client and server, but when the specification is finalized the dependence on GCM will be removed. 

Implementing this would require two additional things to be stored with the user in the database: a list of subscription ids (browsers) and endpoints to call the GCM server.

More details on Google's HMTL5 blog:

http://updates.html5rocks.com/2015/03/push-notificatons-on-the-open-web

**Comment by voat** [comment]
While this sounds exciting and usable, I don't see this being implemented anytime soon because 1) it targets a single browser and 2) only users who enable push notifications in chrome would use this. 

I think it is way too much work for a small subset of voat users. Given all the other open issues, this one would be way down on the list.
