### ISSUE TITLE
Japanese characters are ignored in submission titles

### ISSUE THREAD

**Issue by Luk3M** [voat/voat#411]
Submission used to test: https://voat.co/v/test/comments/87188

The title supposed to be 
`Japanese in Title - 日本人でのテスト`

Result:
`Japanese in Title -`

The characters are ignored only in the title. 

If you try to put **only** japanese in the title, it will get a error for not having enough characters.

**Comment by jksg** [comment]
Not only Japanese, but it seems [all characters above ANSI number 255 are stripped](https://github.com/voat/voat/blob/9c61210c547a84aa5e37bd9aaf8974034f098f7a/Whoaverse/Whoaverse/Utils/Submissions.cs#L90), leaving only basic Latin and some accented characters.

It was a deliberate decision in #330 but I don’t understand why. Unicode can be sanitised instead of completely removing it.

**Comment by DanielFlamino** [comment]
It was a temporary decision until a proper filter was created IIRC.

**Comment by ekg** [comment]
:+1:  for adding full unicode support

**Comment by 39bit** [comment]
For devs: Unicode can be sanitized using Unicode character categories. For example, you could permit characters in these following categories: Lu, Ll, Lt, Lm, Lo, Nl, Mn, Mc, Nd and Pc, as well as all ASCII characters.

For the record, I might try implementing this myself.

**Comment by PuttItOut** [comment]
Closed as this is not a planned change.
