### ISSUE TITLE
reevaluate Technology

### ISSUE THREAD

**Issue by pharno** [voat/voat#445]
"Why was this made?
This was just a hobby project to help me get a better understanding of C# and ASP.NET MVC and Entity Framework."

This tells me that this project was created just to learn those 3 things, meaning that voat was built without greatly evaluating the best technologies for its use case. therefore I ask you to reevaluate the technologies used. 

A few points:
- According to IRC, MSSQL licenses are per CPU (core?)
- MSSQL excludes developers not running windows
- In the future a distributed database might be needed (something like casandra, but thats up to the evaluation)
- Maybe reevaluate the language too. A language that compiles to machinecode is faster, but takes longer to develop usually. those have to be weighted against each other.

**Comment by PuttItOut** [comment]
What you see here has zero to do with platform/language. The bottle necks are elsewhere but hey, let's bash MS.

**Comment by pharno** [comment]
Im not here to bash MS. I know where the issues come from. But in the future, when voat might be very popular, the microsoft stack will just not do it anymore.

http://en.wikipedia.org/wiki/Programming_languages_used_in_most_popular_websites
aside from MS, noone in that list uses the MS stack.

and MSSQL excludes developers not running windows, thats not "bashing MS", thats just plain fact. 

If after a reevaluation the MS stack is still deemed best, so be it. 

"but hey, lets bash MS". sorry that im trying to help

**Comment by Aaronontheweb** [comment]
@pharno cool, someone who wants to replatform a service because of FUD!

> and MSSQL excludes developers not running windows, thats not "bashing MS", thats just plain fact.

Run Windows then, dude. No one is stopping you. And SQL Express is free.

**Comment by PuttItOut** [comment]
The only main argument here is MS SQL. I can understand that to some degree as it's $$$ compared to free, but to say it can't perform is a little ignorant.

And I'll take C# running on Win/Mono before Java any day, any time, any where.

**Comment by pharno** [comment]
I find it concerning that you dont even _evaluate_ it. 

Evaluating technologies is something that should happen before a project is started to ensure that it doesnt run into problems. This doesnt seem to have happened here. If you evaluate technologies now and see that the MS stack runs fine, then do that. But you might find problems with the stack. 

I really dont believe that you can run a website the size of Reddit on this stack.

**Comment by PuttItOut** [comment]
You see, your bias is obvious. It's also obvious you didn't read that these problems have ZERO to do with stack choice. I hope you read the previous sentence.

**Comment by pharno** [comment]
If you dont want to reevaluate your technology, I hope that you are using the correct one for this. Which would be coincidence, but okay.

good luck.

**Comment by Aaronontheweb** [comment]
> I really dont believe that you can run a website the size of Reddit on this stack.

Well first things first - getting to the "size" of reddit is going to be a much harder community / marketing / user acquisition problem than it is an engineering problem.

Cool, and this is based on what evidence? What production data do you have to validate that? Asking because I'm ex-Microsoft and build high-performance tools and frameworks for .NET. 

Right now based on the numbers voat's seen historically it's actually scaling really well, considering that it's running on a single box: https://voat.co/v/voatdev/comments/114435

The architecture and the tools will inevitably need to change, but .NET has proven itself to be able to handle industrial scale. That's why most banks, healthcare companies, and gaming companies (as in, gambling) all use it.

Your comments come across as more of a complaint about the fact that .NET / MS SQL is being used than anything rooted in data.

**Comment by pharno** [comment]
> Well first things first - getting to the "size" of reddit is going to be a much harder community / marketing / user acquisition problem than it is an engineering problem.
of course its hard. but you dont want to change from mssql to cassandra when you have 200million users. 

but as I said, good luck, do what you want. I only asked you guys for a reevaluation. which might have come out to the result that your current stack is fine, but no, you guys just want to continue on your way, without knowing if your stack is the right one or not.

as I said, good luck.

**Comment by Aaronontheweb** [comment]
> but you dont want to change from mssql to cassandra when you have 200million users.

Reddit doesn't have that many registered users IIRC, not even remotely close to that, but I know what you mean.

The stack will inevitably change - I don't think SQL Server is the right tool for every possible thing that can happen in the database layer either (it's simply NOT designed to handle such write-heavy workloads.)

But come on man, go re-read your comments. You're acting like .NET and SQL Server have doomed the site without any actual data. Ultimately the choice of stack doesn't really matter - using it effectively does.

**Comment by rafajafar** [comment]
> Well first things first - getting to the "size" of reddit is going to be a much harder community / marketing / user acquisition problem than it is an engineering problem.

I disagree. For instance, there's a big influx of users right now. This was a great chance to acquire a fuckton of users... and this single box is shitting the bed. You cannot partition your concerns such that engineering is separate from marketing. You need a more gestalt approach.

> The architecture and the tools will inevitably need to change, but .NET has proven itself to be able to handle industrial scale. That's why most banks, healthcare companies, and gaming companies (as in, gambling) all use it.

False dichotomy. You cannot compare banks, healthcare, and gambling companies to this problem. Those applications rely heavily on transactional consistency so they must warehouse, shard, and silo their data to an extreme... by law. In addition, you will never see the demand for responsiveness that you will see with a site such as this. Plus their systems aren't exactly...yanno...cheap. You can solve your problems very cheaply, not just from a software stack standpoint, but from a hardware stand point, if you were not relying on, say, mssql in your data layer. 

Your site isn't working. To get it working with this volume, you will need to distribute your load off of your database somehow. I am willing to be money you are not set up to do so quickly. In fact, with an RDBMs, that's a huge problem. You can't just throw up another MSSQL server and it works... but with stuff like, say, cassandra, you can. 

Sure you could integrate cassandra into you .NET code stack, but you're also going to have some of the worst support for those technologies and the least ability to rapidly adapt to new technologies. 

There is a reason that people use Java and .NET... it solves a business requirement that you do not have. Namely, there must be a support SLA for technology used. There must be a known and endorsed technology in the case of government. It must be built to function within certain security guidelines quickly. Most important, it had to be vetted by various government agencies. That doesn't mean it's the best for your use case... in fact it's quite the opposite. Your software isn't free, and you running it off of a single $50 a month box does not mean that you're not going to kick yourself for licensing issues later... especially if you're locked into MS Enterprise solutions to solve your problems.

Ditch Microsoft. Soon. Or fail. No two ways about it.

**Comment by Aaronontheweb** [comment]
@rafajafar 

> False dichotomy. 

Someone put on their Fedora, trenchcoat, and left home with their book of logical fallacies today! Let's see how well you did.

> In addition, you will never see the demand for responsiveness that you will see with a site such as this.

Cool, so response times for social media commenting website need to be better than FinTech systems? Sooo.... got a source for that?

> You can solve your problems very cheaply, not just from a software stack standpoint, but from a hardware stand point, if you were not relying on, say, mssql in your data layer.

So, what's your experience with scaling costs in production like when licensing fees are involved? Asking because I've built analytics systems on top of .NET, Cassandra, SQL Server, etc... And our costs are driven overwhelmingly by hardware and bandwidth. Like, not even close to being comparable. 

What the .NET stack actually gives you is more bang for your buck per-core because the CLR, Windows Kernel, JIT compiler, etc are all vertically integrated to work together. That's why I can do things like kernel cache HTTP responses in .NET.

> Sure you could integrate cassandra into you .NET code stack, but you're also going to have some of the worst support for those technologies and the least ability to rapidly adapt to new technologies.

Speaking as the author of a [Cassandra driver for .NET](https://github.com/fluentcassandra/fluentcassandra), I would totally agree were it not for the fact that every big data company is scrambling to support .NET and Azure, because rich customers live in that ecosystem. DataStax has a Cassandra driver for C#, ElasticSearch has one, and the list goes on.

> Most important, it had to be vetted by various government agencies. That doesn't mean it's the best for your use case... in fact it's quite the opposite. Your software isn't free, and you running it off of a single $50 a month box does not mean that you're not going to kick yourself for licensing issues later... especially if you're locked into MS Enterprise solutions to solve your problems.

[BizSpark](http://www.microsoft.com/bizspark/) bro.

> Ditch Microsoft. Soon. Or fail. No two ways about it.

Yeah, replatforming will solve ALL of voat's scalability problems. Not, you know, *actually determining what the scaling problems are with data* and then solving them. Plus everyone knows that rewriting an entire project in Node.JS is way faster than say, query-tuning SQL Server or changing the topology of the service.

**Comment by pharno** [comment]
> Someone put on their Fedora, trenchcoat, and left home with their book of logical fallacies today! Let's see how well you did.

was that really necessary?

**Comment by Aaronontheweb** [comment]
> was that really necessary?

No, it wasn't - dick move on my part. My apologies @rafajafar - not cool of me.

**Comment by rafajafar** [comment]
> Someone put on their Fedora, trenchcoat, and left home with their book of logical fallacies today! Let's see how well you did.

I'm going to ignore you said that after this, chief. I will pretend this is an adult conversation among peers. I just want to point out that I don't appreciate your dismissive tone and when you say, ", although delivered in a way that didn't occur for me as 'constructive.'," maybe you should consider yourself part of the problem.

> Cool, so response times for social media commenting website need to be better than FinTech systems? Sooo.... got a source for that?

Happily.

http://www.alexa.com/siteinfo/fintech.net

http://www.alexa.com/siteinfo/reddit.com

First off, FinTech's stuff doesn't load very fast for me at all. Reddit has a global rank of 30 and I'll bet good money it'll load as good in Luxembourg or Norway as it does in the U.S.... so yes, the response times must be better than FinTech, because I don't want to use FinTech with this kinda load time. 

> So, what's your experience with scaling costs in production like when licensing fees are involved? Asking because I've built analytics systems on top of .NET, Cassandra, SQL Server, etc... And our costs are driven overwhelmingly by hardware and bandwidth. Like, not even close to being comparable.

Fine. Let's say you're correct and licensing is a non-issue. You're ignoring two points: 

1. Why are you paying licensing when there are free solutions?
2. What do you actually gain from these licensed products that you wouldn't get from an open source solution?

> What the .NET stack actually gives you is more bang for your buck per-core because the CLR, Windows Kernel, JIT compiler, etc are all vertically integrated to work together. That's why I can do things like kernel cache HTTP responses in .NET.

This is not special in any way shape or form.

> Speaking as the author of a Cassandra driver for .NET, I would totally agree were it not for the fact that every big data company is scrambling to support .NET and Azure, because rich customers live in that ecosystem. DataStax has a Cassandra driver for C#, ElasticSearch has one, and the list goes on.

Are you a rich customer? I'm not sure I see your point here... I actually think you just made my point for me. They're back-integrating technologies to adapt to new technology trends. And they're doing so wayyyy behind the curve. You're a start up, start thinking like one.

> BizSpark bro.

As a member of BizSpark, I know it and it's limits very well. You will not get infinite resources and your benefits will end eventually. This is very short term thinking. 

> Yeah, replatforming will solve ALL of voat's scalability problems. Not, you know, actually determining what the scaling problems are with data and then solving them. Plus everyone knows that rewriting an entire project in Node.JS is way faster than say, query-tuning SQL Server or changing the topology of the service.

I didn't propose a solution to your scalability problems. I told you the thing you need to address first, before anything else. Being on the MS Stack is far from wise. Having worked in the start up scene and dealing with VC the past couple years I can tell you this... you're not going to get your choice of VC if you're using Azure and .NET if you're in a site like this. If you were, say, a cyber security company, yes you would. But you're not. You're in a different crowd, and if they don't hear the keywords they like (such as Linux, AWS, etc etc) they're going to grill the fuck out of you and question your decision making skills. 

Regardless of what you think MS is capable of, there's politics involved with these decisions, too... that's reality, and I'm just giving you a heads up.

> No, it wasn't - dick move on my part. My apologies @rafajafar - not cool of me.

Apology accepted.

**Comment by Aaronontheweb** [comment]
> FinTech

FinTech isn't a specific company - it's short-hand for "financial technologies." Includes HSBC, Morgan Stanley, Chase, CitiGroup, etc...

> Why are you paying licensing when there are free solutions?

Because it's what the Voat founders chose. If you can do better, send in a PR.

But really, this conversation is less than important. I could debate all of those points you raised, but the truth is that voat system is under load and replatforming isn't realistic solution to that in the current timeframe. They need help with their stack as-is.

**Comment by pharno** [comment]
> Because it's what the Voat founders chose. If you can do better, send in a PR.

thats exactly what this whole issue is about. evaluating if the choice of the founder was good or if there is a better one

**Comment by rafajafar** [comment]
@Aaronontheweb 

> FinTech isn't a specific company - it's short-hand for "financial technologies." Includes HSBC, Morgan Stanley, Chase, CitiGroup, etc...

Ahhh ok gotcha. Not a term I was immediately familiar with. Well, I'll tell you this... my bank, CapitalOne, has a terrible website. Very unresponsive. My other bank, Wells Fargo, has gotten a lot better over the years, but they weren't great not that long ago. Now if you're not speaking about the real time processing of, say, stock data etc (I don't think you are) they're not using RDBMs to deal with that. They have very specialized transactional systems for that, and they are (believe it or not) not ACID compliant but use BASE. Anyway, that's neither here nor that because... You Are Not Those Systems. It's like saying, "My truck takes diesel and it can go over mud, so why not use diesel in my hybrid?"

@pharno 

> thats exactly what this whole issue is about. evaluating if the choice of the founder was good or if there is a better one

Don't be a jerk. You can't judge someone as a founder. It's a lot harder than you think. You don't get to pick the founders anyway, dude... it is typically, yanno, the one who got off his ass and did something while you sat around and bitched. Ditch the hate.

@Aaronontheweb 

> They need help with their stack as-is.

Truth. I was just responding to this ticket that was posted in IRC... so it's on-topic, but not helpful right now. Maybe you should mark to revisit later?

**Comment by jbouwens** [comment]
ASP.NET is great, especially with the features in ASP.NET 5. And we don't have to use SQL Server :).

https://www.jeremymorgan.com/blog/programming/how-to-asp-5-linux/

Great ASP.NET applications: http://meta.stackexchange.com/a/10370, https://github.com/Sonarr/Sonarr

If you ask me, the technologies don't need to be reevaluated. The focus should focus on making voat cross platform if we are worried about cost.

**Comment by garethrhughes** [comment]
Rewriting from scratch is never a good approach. There's absolutely nothing about the .NET stack that wouldn't allow you to handle this amount of traffic and far more. Looking at the source it hasn't really been built well for scaling but few web apps actually are at launch. 

There's plenty you could do to optimise the current code and potentially still keep it running on one dedicated box. Depends where your current bottlenecks are, looking at the code I imagine it's database related, or are you just limited by the hosting? MSSQL server can easily handle this site, licensing however might make it not a viable option for scaling.

**Comment by irperez** [comment]
I can tell you as a person who is creating a small side startup, we are definitely running into all of these issues that you guys are mentioning.  We are definitely planning for huge loads (not sure we'll get it but thats another argument) and so MSSQL is definitely out of the question.  But what I found is that almost all open source technologies out there support .Net just fine.  We are looking into a myriad of some nosql solutions as well as some simple key/value stores similar to memcache and some even niche graph databases.  ALL SUPPORT .NET NICELY!

And so yea, we looked at cost.  Its definitely a part of the discussion.  We don't want to pay for licensing.  So again MSSQL is out of the window in that regard.  No argument from me.  But we will most likely need a true RDBMS for portions of our application.  So we are looking at MYSQL or PostgreSQL.  ALL SUPPORT .NET.   

Would I use Entity Framework for this application, that depends.  I like to design the backend with the ability to change the DB Provider.  So I would say its not a lock, but its an option.  But it all depends on the design requirements.  If its a write heavy portion of the app, we might reconsider.

We are also considering running .Net on Linux after .Net 5 comes out.  But honestly, this is the least of our concerns as the pricing between linux/windows in the cloud is marginal at best.

Things have changed greatly in the past 2 years.  The fact that an enormous portion of .Net is now open source has changed everything.  There has been more advancement in .Net in the last year than probably in the previous 4.

From what we've found, the scale factor has more to do with your architecture and scalability design, for example using Akka.net for messaging and more versus straight up ntier.  How you design your nosql systems, sharding, how you utilize quorum between data centers, etc.

Just my 2 cents as a startup founder.

**Comment by rafajafar** [comment]
Yup. Definitely what he said is fine. I'm not a fan of .NET at all as the standards are set for and by MS and MS alone, but whatever... the code's there. 

I would not recommend you continue to try to make a site like this using any RDBMS though.... get as far away from MySQL and PostgreSQL as possible. That's not to say they're bad... they're just bad for this type of application. You're not going to scale with them. Also since it's a link share site, you really don't need much in the way of relational data. There's far better solutions out there that scale horizontally with your hardware.

If you want to keep C#, that's fine, but get away from the rdbms as soon as possible.

**Comment by phillip-haydon** [comment]
This thread is so stupid and pointless. 

These arguments about scalibility are just retarded.

**Comment by rafajafar** [comment]
I found the aspy.

**Comment by luisrudge** [comment]
so.. TLDR is: Stack Overflow doesn't scale?

**Comment by rs999gti** [comment]
Don't feed the trolls.

**Comment by rafajafar** [comment]
Is the site aiming to be like stack overflow or like reddit. Reddit gets more views in a month than the entire StackExchange network gets in a year. 

These are SE's numbers: http://stackexchange.com/about

These are reddit's numbers: http://www.reddit.com/about

If you want to replicate anything, maybe pick something relevant to your model. Comparing StackExchange to reddit isn't reasonable. 

Also you may want to read up on some of the scaling pitfalls reddit has faced.  This is from two years ago:

http://highscalability.com/blog/2013/8/26/reddit-lessons-learned-from-mistakes-made-scaling-to-1-billi.html

**Comment by phillip-haydon** [comment]
Taken from your link:

It’s not necessary to build a scalable architecture from the start. You don’t know what your feature set will be when you start out so you want know what your scaling problems will be. Wait until your site grows so you can learn where your scaling problems are going to be.

**Comment by rafajafar** [comment]
K well this site isn't able to handle the current load, and you already have the exact problems a site like this would encounter spelled out for you in that article, chief. You can keep doing something you know isn't going to work or you can start to plan for what will.

**Comment by phillip-haydon** [comment]
Lol did you even read your link. Reddit uses postgresql. But you're all. Oh no don't use a rdbms because I have no idea what I'm doing.

**Comment by rafajafar** [comment]
Did you read the link? They use it as a KV store, not an rdbms.

**Comment by phillip-haydon** [comment]
I did, and they praise PostgreSQL, and said MOST data, not all, is stored as KV. 

But you said to get as far away as possible from PostgreSQL, without any justifications.

**Comment by rafajafar** [comment]
> I would not recommend you continue to try to make a site like this using any **RDBMS** though.... get as far away from MySQL and PostgreSQL as possible.

I can't believe you're this fucking literal. People like you have seriously turned this into the most retarded github issue thread I have ever seen.

**Comment by phillip-haydon** [comment]
I'm illiterate? We are talking about reddit and your statement. What I just said is completely valid.

Reddit use PostgreSQL.
You said to stay as far away from PostgreSQL as possible.

Stop being a fucking moron.

There's no silver bullet to software, not all problems are solved with document/kv/column databases, and not all problems are solved with a RDBMS. Sometimes one is better suited than the other, sometimes both are required to solve the problem.

This whole thread started because some no0b decided to hate on all things MS and spread FUD, you popped up in here and pipped your own bullshit.

------

While I have 0 care for voat and its problems, the fact you're hating on a project just because it doesn't meet your own agenda makes you look like a piece of shit.

While I gather that voat is having some problems, I can pretty much guarantee, at its current point, technology is not the limiting factor right now.

Either help the guy out, or go shit in your own playground.

**Comment by rafajafar** [comment]
> While I have 0 care for voat and its problems, 

K, and that's obvious because you haven't really suggested anything helpful. So ... bye.

> the fact you're hating on a project just because it doesn't meet your own agenda makes you look like a piece of shit.

What in the hell are you on about, son?

> I'm illiterate?

Obviously.

**Comment by YMIndustries** [comment]
>I'm illiterate?

Nobody called you illiterate.

Loading a single page on Voat at the moment takes upwards of 2 minutes. It is clear that a lot of optimisation will have to be done. Alternative technologies may not solve this problem, but they should at least be fairly considered.

**Comment by phillip-haydon** [comment]
> Nobody called you illiterate.

True, I misread.

> Loading a single page on Voat at the moment takes upwards of 2 minutes. It is clear that a lot of optimisation will have to be done. Alternative technologies may not solve this problem, but they should at least be fairly considered.

Looking at the technology stack. 

EF -> ditch it, materializing objects and change tracking on something that primarily does read's, and where writes most likely don't cross multiple tables, is a waste. May as well just swap this out for something like Dapper.

SignalR -> I can't imagine what purpose this serves if this is just a link/commenting clone of reddit. Massive drain on the server to open up connections that 99% of the time the user doesn't care for seeing updates streamed in. And if the user is opening multiple tabs its even worse. 

So yes, re-visiting alternative technologies is probably a good thing, but there is absolutely no need to ditch everything because it is MS technologies being used. Keep the database, optimize it. Profile the site, see where resources are going, replace bits and pieces as see fit.

**Comment by YMIndustries** [comment]
>SignalR

Oh god I didn't realise that was running. Even just disabling that in times of heavy load would probably fix a huge amount of the performance issues.

**Comment by YMIndustries** [comment]
>EF -> ditch it, materializing objects and change tracking on something that primarily does read's, and where writes most likely don't cross multiple tables, is a waste. May as well just swap this out for something like Dapper.

>SignalR -> I can't imagine what purpose this serves if this is just a link/commenting clone of reddit. Massive drain on the server to open up connections that 99% of the time the user doesn't care for seeing updates streamed in. And if the user is opening multiple tabs its even worse.

I would call those part of the technology that this issue is proposing gets re-evaluated. Those look like two absolutely critical mistakes for a website like Voat.

**Comment by phillip-haydon** [comment]
> I would call those part of the technology that this issue is proposing gets re-evaluated. Those look like two absolutely critical mistakes for a website like Voat.

The points in the original post were:

 * According to IRC, MSSQL licenses are per CPU (core?)
 * MSSQL excludes developers not running windows
 * In the future a distributed database might be needed (something like casandra, but thats up to the evaluation)
 * Maybe reevaluate the language too. A language that compiles to machinecode is faster, but takes longer to develop usually. those have to be weighted against each other.

None of these need to be considered right now. 

But in terms of frameworks chosen then I completely agree they need to be re-evaluated.

**Comment by YMIndustries** [comment]
Pharno provided those as a few points that they felt were worth discussing, but that doesn't mean this issue is exclusively about them.

**Comment by lwansbrough** [comment]
MongoDB is web scale.

In all seriousness though, why are we even talking about this? Pretty sure voat isn't even running the DB separate from the rest of the stack. That's scalability 101. Can we discuss high performance read/write systems when they're actually necessary? MSSQL is capable of handling this load, so is Postgres, so is MySQL - it just depends how much infrastructure you want to build. Cassandra isn't a free win, either. Everything takes time to implement and each has its own drawbacks. The site is built in C# .NET, no one is going to rewrite it - get over it. C# .NET is a great language, and is open source just like the rest of them.

Seems like some people in this thread are forgetting that .NET is developed by one of the largest software companies in the world, and they know a little bit about how scaling works. Ever heard of Windows? Xbox Live? Yeah. Personally I use a more classic FOSS stack, but it doesn't matter. Honestly. 

This site - the entire thing - was running on 1 machine yesterday, can we take a step back and remember that? Step 1 is separating the stack into components. Step 2 is horizontal scaling of each component as necessary - scaling needs to happen fast and it's going to happen at a significant cost. Horizontal is the only way to go in this timeframe. I don't care if you can get N times more writes with Cassandra. Step 3 can be vertical scaling. That's when Cassandra et al can be evaluated. Only once the site is responding does any particular piece of technology matter.

**Comment by YMIndustries** [comment]
I definitely don't think Voat is [ready for Cassandra](http://blog.parsely.com/post/1928/cass/?q=1). What about the technologies Phillip Haydon pointed out? It seems like SignalR could be disabled (at least in times of heavy load) with very few ill-effects and EF is likely adding a substantial amount of time to every single page load.

**Comment by lwansbrough** [comment]
@YMIndustries Are you replying to my comment? You seem to have missed the point entirely. Cassandra is irrelevent. MSSQL is irrelevant. Technology is irrelevant. Throw money at servers. That's the only thing you can do right now. Leap of faith - throw your savings at servers. That's the only way.

**Comment by YMIndustries** [comment]
I'm not convinced that scaling is the be all and end all. The current issue likely will only be saved by scaling as the influx of visitors has been insane, but if the code can be optimised even by 10% (which considering the nature of Voat shouldn't be impossible to achieve) then it will save a substantial amount of money in operating expenses. The issues in the code that aren't fixed will end up costing more in ongoing expenses.

**Comment by rafajafar** [comment]
I want to be that pompous ass and remind everyone that the purpose of a ticket is to bring to the front an issue and deal with that issue. The immediate issues are absolutely pressing and either hardware or something like cloudflare are the only likely immediate solutions... that said, the topic of the ticket was "reevaluate Technology" so saying, "talking about it wont help now" is, of course, not the purpose intended here. Somehow this ticket turned into a comment thread on Voat LOL. :-)

**Comment by funkytaco** [comment]
I have a novel approach to this, based on my studies in Enterprise Architecture. The public should not be deciding how to architect your solution. You need somebody with the knowledge to do this. If you don't have anybody, pick your most qualified person. It can always be reviewed by bringing it to "the business". In your case, you could come back to something like this github issue for community feedback, since you don't have stakeholders.

Take a look at https://store.opengroup.org/catalog/images/N112cov.png (yeah it's a sample,you have to register at OpenGroup to get the full catalog).

First, you need a vision to establish the goal.

Second, you need to get a baseline of the current architecture, then one of your target architecture. The gap analysis done here will help you determine how to road map.

I don't recommend the back & forth approach on this. Have somebody architect this and get a team (of 1+ people since you're a small organization) together. Then, when you have a general idea (pick the technologies later), you can have the "stakeholders" (i.e. helpful voaters on github/voat.co) give feedback.

If you look at the graphic, you will see there are many more steps, but you are in the prelim phase, and should focus on Phase A through D right now. 

There are many architecture frameworks you could use, but I recommend this one (TOGAF 9.1) in combination with the Zimmerman framework. They are both flexible.

I offered my help in that other thread but I removed my comment, as this seemed the more relevant thread. Contact me if you need any advice as I work for a major ISP and have experience with scaling solutions (no charge, but no guarantee on response time). Good luck, guys.

**Comment by sdegutis** [comment]
One option is to rewrite the website in Rails. It wouldn't benefit performance, since Rails isn't known for being fast. But it's also not significantly slower either. It would help with rapid development, since Rails was meant for that. But the main benefit is that tons of people know Rails, so way more developers would be able to jump in and help out. Personally I don't like Rails, just throwing this out there as an option since it was brought up in the unrelated issue #452 which was since closed.

**Comment by pharno** [comment]
this issue has also been closed 2 days ago btw

**Comment by sdegutis** [comment]
Oh.

**Comment by johnduhart** [comment]
> The public should not be deciding how to architect your solution.

@funkytaco I don't think you understand how opensource works.

**Comment by sdegutis** [comment]
@johnduhart At this point I'm betting another reddit-clone will overtake voat in popularity due to darwinistic principles.

**Comment by funkytaco** [comment]
>@funkytaco I don't think you understand how opensource works.

@johnduhart I love open source. That statement has nothing to do with programming. It has to do with architecture and the business. Look at projects like io.js and node to see how you need a steering comittee to make sure you have a clear vision. That isn't normally decided in a forum like this.

**Comment by lwansbrough** [comment]
@sdegutis Seriously? A rewrite? C# is one of the best languages out there both for rapid prototyping and long term support. I don't even use it that often but I can appreciate how mature and well thought out it is as a language. Ruby is a toy language, and rewriting in Ruby would be taking a step backwards both in terms of development time and language capability.

Everyone here seems to be suggesting another language as though C# is doomed. What the hell? It's one of the most widely supported languages in the world in terms of development and is backed by a multi-billion dollar corporation which has open sourced the entire stack required to run it. C# is faster than anything else suggested here so far, and it's ease of development is also paralleled with anything mentioned here - not to mention vote is already programmed in it! Are you guys serious? EF isn't great but it's not the thing that's stopping Voat's growth. Has anyone in this thread **actually** had to deal with scalability before?

The amount of MS hate that's going on in this thread is absurd. Voat's current stack is solid - licensing may need to be addressed, but the bigger issue is with **hardware**. No one has suggested any fixes that address the **ACTUAL** technology problem that Voat is facing right now - you know: servers.

In my opinion, the fact that thousands of dollars weren't thrown at servers 3 days ago in order to deal with the influx of users is a testament to lack of readiness of the developer(s). It's not their fault that they weren't ready, who could have predicted what happened - but the fact that the site is still down is telling. 

The **only** real technology problem Voat faces currently is a hardware one. Software stack is so unimportant at this point I'm actually astounded at the number of people who are in here suggesting their favourite stack as a solution. It. Doesn't. Matter. Twitter ran on Ruby for years, and Ruby isn't anywhere close to being as fast as C#.

Voat has already lost most of its interest because of the lack of response by those involved. The only worthwhile move remains as a hardware fix, but the ROI has diminished substantially. A rewrite is a great move if you're looking to ensure the total failure of the site as a business in the short term.

**Comment by rafajafar** [comment]
Can someone just end this ticket already? I know it's closed but I am getting tired of this getting bumped by people that are jumping in and saying the same shit that was said days ago and acting like it's new. 

A: I hate MS! 

B: I love MS! 

A: I don't see why we should change! 

B: I think we should change! 

A: The hardware's the problem! 

B: We know but that's not what this ticket was created!

A: Then why are we talking about it?

B: Because that's the topic of the ticket!!

C: I think we should use X stack!

A: Oh my god you're dumb!

B: Here we go again!!

**Comment by sdegutis** [comment]
Sorry I'm not here to argue or debate. I'm not a fanboy for any particular language. They all get the job done just as well, roughly. So I don't really care. Unsubscribing now. Thanks.

**Comment by funkytaco** [comment]
@rafajafar, @jksg and @pharno both referenced this thread.

Either way, I think this discussion is pointless & I'm not helping, so I'm going to unsubscribe. I'll check back later to see if there's another channel given to us we can communicate more effectively.

**Comment by jksg** [comment]
@funkytaco I referenced this thread to send the idiots here to argue ;) Take that for pinging me while you unsubscribe! (Unsubscribing too…)

**Comment by StephenCasella** [comment]
I'm late to the boat boat but came here to contribute as a developer and
saw this... Someone needs to say what I'm going to say and for sanity's
sake I will. Everyone discussing this language is faster/better/etc than
that one is completely missing the point. What problem are we trying to
solve with this discussion? If one of performance, we have much more to
gain by restructuring and optimizing than by rewriting to save milliseconds
in execution speed. If one of developer availability, I can name at least
50 developers well versed in the .Net stack, only two of which are familiar
with rails. If one of art and principle, this is not a research project but
a product and there is value in working code. Since what exists already has
value it stands to reason that the risks should be analyzed before
suggesting ideas that can impact that value. A rewrite even in
theoretically perfect technology will add bugs, reallocate the existing
limited effort towards activities that either attempt to regain or add no
value, and impact the timeline, all for the sake of language or stack
preferences.

What problem is being solved and how is a solution this dramatic worth the
risks? Let's discuss that before pledging allegiance to our favorite tech
stacks.

**Comment by rafajafar** [comment]
Can we lock this issue somehow?

**Comment by funkytaco** [comment]
@jksg i see
