### ISSUE TITLE
Scalability super fun time

### ISSUE THREAD

**Issue by Aaronontheweb** [voat/voat#446]
So, some of the stuff brought up in #445 were fair points, although delivered in a way that didn't occur for me as "constructive." Given that the site is 503-ing a bunch right now, it's probably a good time to talk about scalability.

First, and most importantly: @PuttItOut and @voat - can you guys actually afford to run more servers? If not, then we should talk about doing something to help with that.

Second: are you open to having me and others help on scalability issues? Some of the stuff that we might propose may involve expensive stuff like "migrating comments and votes off of SQL Server"

**Comment by PuttItOut** [comment]
It's a question of time and money. It's not hard to figure out how to scale, what's hard is the time investment to do it as well as the funds to accomplish it. If Voat was VC funded it would be done. That is not the case currently.

**Comment by rafajafar** [comment]
Do you want VC? If so, you have sufficient traction to acquire at least $1m USD in seed capital if you were to come up with a business model that works. I can help you brain storm with that, if you like.

**Comment by PuttItOut** [comment]
@rafajafar I'd rather not discuss funding topics in a public forum, but yes, Voat is seeking funding. 

@Aaronontheweb Yeah, we need to throw more hardware at this ASAP. After hardware we really need to look at inefficiencies in the code as there are a lot of them currently. With the API on the horizon we have some concerns that are pressing.

**Comment by Aaronontheweb** [comment]
> Yeah, we need to throw more hardware at this ASAP.

Probably should get started on that now :p 

> After hardware we really need to look at inefficiencies in the code as there are a lot of them currently.

If your issues are architectural, optimizing code won't make much of a difference. 

I'm hellishly busy for the next couple of days, but let's set up a time to talk on Skype next week or on Sunday. I'll DM you on voat.

**Comment by PuttItOut** [comment]
> If your issues are architectural, optimizing code won't make much of a difference. 

It is a combination of a few things but yes, agree, optimization wouldn't put a dent in this particular issue. 

I'll look forward to discussing. Please do PM me.

**Comment by rafajafar** [comment]
@PuttItOut add me on hangouts if you like... same username at gmail dot com.

**Comment by jorgeavaldez** [comment]
Hello!!! I would like to help as much as I can!!! I would not call myself an expert in C#, but I have worked with it at work (mostly for desktop applications) and am fully willing to help out in any way that I can.

**Comment by sergiotapia** [comment]
Reddit is in full-blown sinking mode at the moment. I think Voat is going to need to scale as soon as humanly possible. Now is the perfect time to capture those people leaving Reddit.

See current -> http://reddit.com/r/all

**Comment by choikwa** [comment]
holy trinity of doge! that is some titanic moment at /r/all

**Comment by yotamN2** [comment]
I'm not an ASP.NET developer (front-end and nodeJS) but I surprised to see that the pictures are not compressed, I just wanted to see how much it can save:
![](http://i.imgur.com/hPaIeUa.png)

Also it's would probably be smart use front-end rendering (react or angular), it's will really help the server but sadly it's will require almost complete rewrite.

**Comment by Saturate** [comment]
I think CloudFlare.com could help a lot with caching and performance :-)

**Comment by manuelgomes** [comment]
Risking sounding foolish for not knowing the specific techs involved, there's a couple of obvious things:
* Segregate your reads from your writes on the DB side, you can have a master and a bunch of replicating slaves. I'm sure MSSQL has something along those lines
* Session store: if it's in the DB... fine, scale along with it (for the time being), if not remove it from individual nodes because local storage would prevent the following point, I would suggest redis as a session store, but... sure, whatever works.
* More app servers. With segregated reads and writes, and no local storage on any app nodes... go crazy, more web nodes behind a load balancer for the immediate win.
* Static assets (css, js, et al) and user content offloaded to a CDN. It's not just a binary delivery speed gain, it's less web processes picking up the same old stuff.
* Fragment cache and so forth are probably a good idea, but that's a less immediate concern because it takes more time to implement, and one should probably re-evaluate architecture and/or platform before embarking on that degree of change.

Happy to discuss any of these that sound applicable. I feel lazy for not figuring out which are from the code, but... last time I dealt with the MS stack was in the late 90s, so I wouldn't be counting on me for much actual code :)

**Comment by Daniel15** [comment]
@Saturate Cloudflare only really helps with static content, not with highly dynamic content.

> Yeah, we need to throw more hardware at this ASAP.

Also consider Azure or AWS  rather than physical hardware.

**Comment by rogeralsing** [comment]
@Daniel15 
>Also consider Azure or AWS rather than physical hardware.

http://highscalability.com/blog/2011/3/3/stack-overflow-architecture-update-now-at-95-million-page-vi.html

Stackoverflow.com runs on .NET on physical HW, and not that many servers considering their load.

**Comment by JTtheGeek** [comment]
>Stackoverflow.com runs on .NET on physical HW, and not that many servers considering their load. 
StackOverflow was using about 27 servers at the time that was written, with mixed architectures and a very wide array of services and systems to manage.   That's quite a nightmare to support.  I would highly recommend Azure/AWS to take care of the management of hardware.   Personally for .net based projects Azure is pretty awesome.  Would be happy to help out in deploying to Azure or guidance on working with Azure.  Azure DocumentDB would likely be a good fit for most of the site's voting system, SQL as service should be able to handle the general data.

**Comment by mikeyoon** [comment]
I'd agree that for a product of widely unpredictable load (e.g., the hype could be dead next week), a cloud service would be much better. StackOverflow was developed before PaaS stuff was good. Based on a cursory glance at the code, I think an improvement with a big payoff would be the addition of a caching layer such as Memcache or Redis. Hitting the SQL server for every request is pretty expensive to scale. So short term I'd recommend the following:

* Split the SQL and Web app onto two or more systems.
** Due to hitting the SQL server for every data-driven request, I imagine this will hit a wall relatively quickly
* Implement a caching layer for posts and comments so you don't put so much load on the SQL server. This will allow you to horizontally scale the web servers more effectively.

There's certainly a lot more you can do, such as implement a no-SQL tier in there to use as a secondary store, which would help a lot with anyone spamming writes into the site, but certainly a lot more work involved.

**Comment by Daniel15** [comment]
One of the nice features of Azure's PaaS is that it can automatically scale
up and down based on load. With physical machines, if you get enough
machines to handle your peak load, they'll be sitting doing nothing most of
the time.

I'd suggest profiling the code and checking which processes are using CPU
on the server to figure out where the bottlenecks are. You might be IO
bound rather than CPU bound, in which case a faster disk (eg. SSD) would be
most beneficial. Caching is always beneficial, but SQL servers are actually
quite good at handling heavy load, even without a caching layer. At my
previous job they handled a huge amount of load (millions of hits per week)
with no caching layer, just a handful of servers and an F5 Big-IP load
balancer.

**Comment by rogeralsing** [comment]
>StackOverflow was using about 27 servers at the time that was written

1. They have stated that they have a lot of redundancy and could run on 5 IIS servers if I recall correctly.
2.They have "a few" more users than Voat..

There are a lot of lessons to learn from the SO architecture.

Cache everything. SO uses 3 levels of caching. http://meta.stackexchange.com/questions/69164/does-stack-overflow-use-caching-and-if-so-how

Use a micro ORM for reads instead of EF, e.g. Dapper.
Fetching tracked entities is expensive, compiling linq to sql statements is expensive.

**Comment by ryanelian** [comment]
http://stackexchange.com/performance

With 27 servers, their peak is only 10%. I think they can survive with much less than 27 servers.

We might be able to offload the searching feature of the voat using Google custom search instead. And yes, we should cache.

We can live with EF for now. Contrary to popular beliefs, it's actually very fast if you write your EF optimally (mostly has something to do with avoiding Lazy Loading and/or turning off change tracker / manually detecting changes).

**Comment by rogeralsing** [comment]
>We can live with EF for now. Contrary to popular beliefs, it's actually very fast if you write your EF optimally (mostly has something to do with avoiding Lazy Loading and/or turning off change tracker / manually detecting changes).

Yes, I'm one of the EF6 contributors and wrote some of the linq translation code for it.
Selecting into projections is much faster than selecting tracked entities.
But you still have to carry the CPU based load of translating Linq into SQL, that code is pretty hairy on the inside.

**Comment by funkytaco** [comment]
@manuelgomes made a lot of good points. Cloud Flare helps the Denial of Service, which can even happen from legit users hitting F5. I've also helped customers with other DDOS solutions that mask the DNS of the target IP.  @PuttItOut  Once attackers have your target IP address, they can bypass any solution you come up with, so never share that address.

Static assets (CSS, Javascript, libraries) should be bundled into one file to reduce HTTP calls. They should also be minified (compressed). 

Let's also keep in mind that the Stack Exchange websites are much more reactive than Voat.co currently, so they're going to need to spin up more cpu/memory to compensate for now.


Concerning the current migration, I don't see why you are experiencing downtime. I would highly look into a snapshot/backup regimen so you occur zero downtime during a migration (i.e. Veritas Netbackup/IBM Tivoli)  or even rsync for the dirt poor if you can't afford snapshots yet.

@PuttItOut As I mentioned in a posted I deleted before (due to the bickering in the thread), I actually work for Stack Exchange's hosting company and have been in the webhosting industry for a long time. Obviously, I cannot discuss their solution, but may be able to field questions concerning architecture. As mentioned before, I'd consider looking at TOGAF 9.1 combined with the Zimmerman framework to get a roadmap for where you want to be. 

Good luck to you guys.

 - Luis

**Comment by Daniel15** [comment]
> Static assets (CSS, Javascript, libraries) should be bundled into one file to reduce HTTP calls. They should also be minified (compressed).

Voat is already bundling and minifying CSS and JavaScript :) Serving them off a CDN is a good idea though, and fairly simple if using a CDN that supports origin pull.

**Comment by Aaron-P** [comment]
> Voat is already bundling and minifying CSS and JavaScript :) Serving them off a CDN is a good idea though, and fairly simple if using a CDN that supports origin pull.

It isn't when I look at the front page.  The files are being added to the bundle config but are being output as separate, unminified files.  Is the bundler not enabled?

**Comment by Daniel15** [comment]
> It isn't when I look at the front page.

That's strange. It was minified/combined last time I viewed the site, but now it's not.

One other scalability issue I see is that Voat is using sessions: https://github.com/voat/voat/blob/cad35c1647e651c572c791353f44364288f482dc/Whoaverse/Whoaverse/Global.asax.cs#L61. The default session provider acquires a write lock for every request (see http://stackoverflow.com/questions/3629709/i-just-discovered-why-all-asp-net-websites-are-slow-and-i-am-trying-to-work-out). I'm not sure if you're using a custom sessionstate provider or not.

**Comment by Daniel15** [comment]
It's possible it's not minified/combined if the site is running a debug build (which should really never happen in production). It's difficult to tell if the site is running a debug build or not though.

**Comment by steakknife** [comment]
Using Azure or AWS will lead to Voat being beholden to American corporations and their insanely complicated, broken commercial law. 

Bare metal is cheapest but it is often underutilized.  VMware, Xen can help with that.   I would avoid OpenStack unless one has a dedicated team of Python devopsers since it requires loads of hacks and maintenance to do even the simplest thing.

(Ran mail-hosting m&a startup ops in London)

**Comment by funkytaco** [comment]
Common upgrade path regardless of provider: throw cpu/memory/disk at it, until you find an architecture that works. I would highly suggest it's thoroughly thought out before you end up migrating endlessly. The hosting provider near disaster is a good example of why offsite backups are an absolute must. Absolute must. I cannot state how important that is. Snapshots are good for a disaster, but offsite backups keep you in business. 

I was working at an ISP where Couch Surfing went down due to corrupt backups (partly their fault, partly my co-workers fault) and nearly threw in the towel. They were only saved by the user base who willingly re-registered.

**Comment by steakknife** [comment]
@funkytaco And test backups regularly (restores to temp/alt locations), because untested backups are often worthless even though they appeared to be doing something.

[Tarsnap](https://www.tarsnap.com/) (via cygwin) for crucial stuff, [SpiderOak](https://spideroak.com/) and/or (encrypt first) [BackBlaze](https://www.backblaze.com/) for everything else.

**Comment by funkytaco** [comment]
@steakknife All good advice. 

Snapshots are the quickest way to recover in a restore. Replication works better in Linux environments because it's easier to just rsync and forget about it (Windows isn't as forgiving as it really depends on the software being used).

On a side note, what you didn't say is you're recommending backup providers who can't snoop on your data it seems. That may or may not be a priority for them (I'm not saying it shouldn't be just something of note). But anyhow, I use the free SpiderOak and they seem decent. BackBlaze is also pretty solid, but I'm not sure about the others.

**Comment by Aaron-P** [comment]
> One other scalability issue I see is that Voat is using sessions
The only thing I see it using session for is theme, which is completely unneeded.  The theme selection should be rolled into the identity and put on the client side getting rid of session completely.  Being as stateless as possible on the server is better than doing custom session storage rigamarole.

**Comment by Daniel15** [comment]
> The only thing I see it using session for is theme, which is completely unneeded.

In that case it should be a pretty easy perf win. Could probably just move theme selection into a cookie :)

**Comment by Aaron-P** [comment]
If it were attached to the identity with a claim then it would go along with the identity cookie, plus the benefits of having fewer overall cookies + crypto/signing that already goes along with it.  Since the theme selection is being stored on the server side anyway and can't be entirely client side I'm not sure there would be any benefit at all to a separate cookie.

**Comment by funkytaco** [comment]
I agree with @Aaron-P. Put it with the Oauth identity if that's all that was in the session.

**Comment by Daniel15** [comment]
:+1: Sounds good

**Comment by Aaron-P** [comment]
Are private messages really important enough to need pushes? I don't think SignalR is adding a whole lot for the need to have open connections vs having a standard REST api that can cache responses.

**Comment by PuttItOut** [comment]
Closed as codebase has changed significantly
