### ISSUE TITLE
A pull from reddit feature to mirror sub-reddits/posts before they are deleted

### ISSUE THREAD

**Issue by akshetpandey** [voat/voat#447]
See title.

Can we have a discussion on this?
We can create shadow users with "reddit-" prefixes if required.

**Comment by fractalwrench** [comment]
What's wrong with archive.is? I don't see why this feature needs to be integrated into Voat, a 3rd party service makes more sense.

**Comment by akshetpandey** [comment]
archive.is remove the possibility of continuing the discussion. Its a good way to take a snap shot, but it is basically just that, a snapshot of the discussion, not a way to continue it.

**Comment by moeVoat** [comment]
You can continue it on the discussion page for the archive.is link post.

There's no point in being able to reply to specific comments because the Reddit accounts do not exist on Voat and the original commenter would likely not reply. Seems like a complete waste of effort and space hosting the thread on Voat when archiving it is a much simpler and just-as-effective solution.

**Comment by faissaloo** [comment]
I second this, I want to be able to continue the same discussions

**Comment by DanielFlamino** [comment]
Archive websites already serve this functionality. Simply archive the initial conversation and like @moeVoat said, comment on the discussion page for the archive.

**Comment by funkytaco** [comment]
:-1:

**Comment by talons1337** [comment]
Basically what @funkytaco and @moeVoat said.

**Comment by PuttItOut** [comment]
Closed as this is not a planned feature.
