### ISSUE TITLE
Voat is on fire. What can I do to help?

### ISSUE THREAD

**Issue by WardBenjamin** [voat/voat#452]
In all seriousness, is there a plan for more hardware? I'm interested :)

Also, what can I do to help? I have a large amount of experience with C# and some with ASP and SQL. What needs done?

**Comment by jrcharney** [comment]
Keep calm.  Most of the incoming traffic isn't so much people who want to uphold free speech online, but to post hate speech in front of a captive audience. (Apparently, 4chan or whatever other imageboards they haven't though about using) aren't good enough for them to use.

I'm coming back to Voat to enforce a few groups I adminstrate because /u/Ferguson is NOT like /r/Ferguson.  My home town is NOT a toilet for racists to come and shit their racist propaganda or the bullshit whatever RWNJ with a mic or blog to post racists crap!  (If I would have known the hate speech folks were coming this way, I would have come back a couple of months ago and established /u/Coontown to be a subverse (subverse : voat :: subreddit : reddit ) to post funny pictures of RACOONS in little hats.)

Needless to say, the fact that there is traffic to this site still kinda makes Voat a success, especially since there should be an alternative to Reddit.  (Competition is good!)

Needless to say, I'm feeling a lot like a wild west sheriff right now, waiting for the banditos to come into my subverse so that I can pick them off like the insects they are.

I'm ready to kick ass and chew bubble gum...and I'm all out of bubble gum.

**Comment by jcrza** [comment]
jrcharney what a weird comment to leave on GitHub

**Comment by WardBenjamin** [comment]
@jcrza Yeah, I agree with you. I was more leaning towards what I could do to help the Voat platform more than the community itself (which can take care of itself IMO). Programming, man. That's the life, it's what I do.

**Comment by jrcharney** [comment]
Nevermind, forget whatever I said. I'll be trying to make the community better, especially since I don't do C#.

**Comment by sergiotapia** [comment]
@jcrza: Agreed... ![http://unbounce.wpengine.netdna-cdn.com/photos/ce5.gif](http://unbounce.wpengine.netdna-cdn.com/photos/ce5.gif)

**Comment by sdegutis** [comment]
Hahahahahaa, C#.... but yeah it's not *that* bad a language. Anyway, I'd love to help too if possible. Any current plans on making it scale better?

**Comment by mlwohls** [comment]
Anyone have any contact info for the founders?  My startup's engineering team is f'n amazing at scale (heck, or VP of Eng built Netflix's architecture).  We need a fun distraction + we'd all love for VOAT to win.  Any help in connecting us to /voat would be great to see how to best help.  We're already working on setting up a scalable AWS instance.  Shoot me a note here or at mlwohls2@gmail.com.  Thanks!

**Comment by sdegutis** [comment]
In all seriousness, how tied are you to using C# for this? You could probably get *way* more help if it was written as a Rails app instead.

**Comment by sergiotapia** [comment]
I would have loved it to be Rails as well. Incredibly quick to add features, speed won't be much of an issue we could just fragment cache everything and throw a large memcache on it. @sdegutis I'm interested!

**Comment by funkytaco** [comment]
Hey guys, I have an extensive range of IT skills, so I'm going to offer one tip which will work wonders.

Sign up for cloudflare. It should just work with your existing setup. Static assets will then be served via the cloudflare CDN and stop round-trip visits to your server (one server, right?). There are other things you definitely should do, but that is the very least. 


On the topic, I'd like to offer sysadmin help in my discretionary time, as I believe in this project. I'm currently studying for Enterprise Architecture, so I feel like this would be a good way to help showcase my skills for a good cause. Just to back up my skillset you can check out my profile at https://www.linkedin.com/in/luis1
I currently work for the #2 ISP in the world (we hosted YouTube until they got bought out. We hosted Battlefield 3 servers (in the hundreds), and still host Square Space, Wordpress, Stack Exchange, to name a few. Currently, I'm a software developer, but I've also been a sysadmin, DC tech, ADSL/Cable/Dial-up Support / NOC ... the list goes on. If you're not interested, I welcome you to fire off a message to me occasionally as I know a little bit about many IT fields, or at the very least I can reach out to somebody who might be able to.

And some unsolicited advice, you'll want to plan your upgrade and not just throw cpu, disk, and memory at it. Get a baseline of your current data architecture and your target architecture and go from there. There are ways to iterate via a roadmap to where you want to be.

Good luck! I'd hate to see how many member signups you're losing right now, but at least you've come up with something better than the 503's from yesterday! You guys can do it - nobody else is in a better place to climb up the ranks and surpass the big guy.

**Comment by jrcharney** [comment]
I agree with @sdegutis. Since Reddit is practically Python powered, Voat should strive to be Rails developed.  Not to mention all the stuff that seems to work with Ruby. (JRuby, NodeJS, etc.)

**Comment by pharno** [comment]
maybe the decision on what to use should not be something political ("Since Reddit is practically Python powered, Voat should strive to be Rails developed. "), but rather what the best Stack for it is as a whole.

**Comment by sergiotapia** [comment]
Make no mistake that C#/MVC is going to be faster than rails more often than not. If (and I doubt it) Voat migrates to Rails it's going to be to increase development speed, but performance. Which isn't to say Rails is slow. It's easy to make that kitty purr.

**Comment by pharno** [comment]
Technology has been heavily discussed in #445

**Comment by jrcharney** [comment]
@pharno I was thinking of trying something different, not so much in a matter of politics but in technology.

**Comment by pharno** [comment]
well, but that would really mean evaluating all kinds of technology and choosing the best out of them. not doing rails just because reddit happens to be python.

**Comment by jksg** [comment]
I don’t like or use C# myself, but these suggestions are absurd. Why should Voat be in `$language`? Voat isn’t a vague idea or a planned project; *it already exists in C#*. If you want to write a new reddit-clone, or port Voat to `$language`, nothing is stopping you.

Everyone suggesting a change of technology is just trying to get a finger in the pie because Voat has a head start as the popular reddit alternative right now. Voat got lucky and good for them; they put in the hard work in the past 1–2 years *in a language of their choice*.

If you hurry you can still get your own `$language`-based reddit alternative in the spotlight — you’ll probably even overtake Voat, since `$language` is so much faster/better/harder/stronger and C#/ASP.NET/MSSQL sucks so bad, *surely* you’ll be able to handle the influx of visitors and have none of the performance/scaling problems that Voat is facing now.

The next /r/announcements could happen any time. One month? One week? Tomorrow? Stop commenting and start coding! `$language` is great for rapid prototyping and deployment, right? ;)

**Comment by fractalwrench** [comment]
+1. If you want to help Voat the best way is to send Pull Requests to existing issues, donate to the server fund, or help test the new API. Bashing C# is not going to achieve anything other than potentially distracting the Voat devs at a time when they're very busy.

This ticket should be closed as it's not really an issue with the code.

**Comment by WardBenjamin** [comment]
The original idea for this ticket was to find out what I could do to contribute to voat. It's wildly diverged for.... some reason. Closing for now.
