### ISSUE TITLE
"Heavy load" error page should not redirect

### ISSUE THREAD

**Issue by lyndsysimon** [voat/voat#454]
When attempting to load a page while Voat is under heavy load (or, presumably, DOS), the user is redirected to an error page (`/error/heavyloadgonefishing`). When this happens after opening a window in a new tab, there is no way to go back to the page that was requested.

Loading the error page at the URL the user attempted to access would preserve the intended URL, and allow the user to refresh the tab later.

**Comment by God--owner-of-the-universe** [comment]
I thought that, too, but assumed that this was intentional *for the time being:* It prevents additional load from too much refreshing. Voat is really crawling on its teeth these days (reddit influx), plus I heard that eventually, the backend would need profound changes because it only scales that far, so this might be a desperation measure.
