### ISSUE TITLE
CPU utilization

### ISSUE THREAD

**Issue by voat** [voat/voat#465]
My main concern for the time being is CPU utilization (primarily IIS since SQL server is handling the traffic very well) and I would love if people who are willing to contribute would dig deep into voat codebase to find any areas which are CPU intensive and address those or if unable to contribute, bring my attention to said areas so that I can find alternate solutions. Thank you! /Atko

**Comment by inkadnb** [comment]
I missed this post but addressed this in another issue. EF has quite a bit of overhead. I'd be willing to help with utilizing a micro-ORM solution such as Dapper. We should be able to utilize the existing EF generated model objects and treat them as POCO objects.

I'm hoping we can do this gradually to address problem areas in particular.

**Comment by glugalug** [comment]
Possibly related, I was looking through the SQL to figure out why looking at your received messages usually times out, and noticed that there are no indexes defined in https://github.com/voat/voat/blob/master/whoaverse.sql, other than table primary and foreign keys.  At first I thought I must be missing something because that wouldn't scale at all, but from stackoverflow questions like this, I think maybe when you are using non-indexed columns Entity Framework could be moving the where clause filtering logic from SQL Server to the client.: http://stackoverflow.com/questions/12846913/ef-not-executing-where-clause-at-db-level

Are there indexes on Recipient and other columns that occur in where clauses that I am just missing?

**Comment by lawl** [comment]
I'd love to help with this, but I'm a Java guy so...

I did however work on performance for large scale java deployments in the past, so I dunno if it's of any help, but randomly poking around in the source usually doesn't get you very far.

Here's what you should do:

1. Identify the most commonly requested pages (main page etc.) from live traffic. You should probably provide like the top 10 visited views so performance bottlenecks in those can be identified.
2. Run a profiler in your development environment while running a profiler, for Java there's [JProfiler](https://www.ej-technologies.com/products/jprofiler/overview.html) for example. [Visual studio seems to have something built in?](https://msdn.microsoft.com/en-us/library/2s0xxa1d.aspx)

You can't really do much otherwise because you don't actually have an idea what is eating up your CPU time if you randomly poke around.

**Comment by pharno** [comment]
@lawl new relic can help identify the pain points easily.

**Comment by lawl** [comment]
@pharno I usually trust your judgement :) But this seems like it's some always on kind of thing?

Does it give you a per-breakdown etc.? If it doesn't it's useless in this case. If it does it needs to <java:lingo>instrumentalize all the classes</java:lingo> which would further hurt performance so I'm not sure if that's a sensible option right now.

**Comment by pharno** [comment]
performance hit is below 5% afaik. Not only does it provide a per method breakdown, it does the entire call graph, across servers if needed. 

I suggest you try the trial. Unfortunatel its proprietary, but I think with the trial you should be able to find a lot of performance issues.

![Example](http://blog.newrelic.com/wp-content/uploads/blog_python_5.jpg)

**Comment by lawl** [comment]
Meaning for this case it's pretty much useless in my opinion, you want to profile locally first and grab the low hanging fruits before you start doing that, from the loading times even behind cloudflare I think 5% would hit it quite bad, but yeah, obviously only @voat has the data to judge.

Nevertheless without a per method breakdown I think it's pretty much useless at this point.

**Comment by pharno** [comment]
Im sorry if I was unclear, it _does_ do the per method breakdown.

it also shows which pages are called most often, which take the longest, why they take so long, longest DB queries, etc.
