### ISSUE TITLE
Allow varying degrees of anonymity for anonymous subs, and add 8ch integration/cooperation

### ISSUE THREAD

**Issue by kiwikku** [voat/voat#470]
Anonymity shouldn't be an all or nothing deal. Currently when you make a subvoat anonymous, everyone is forced to comment anonymously and voting is disabled. I'd like to see more options in the settings which let board owners fine tune the anonymity of their board. Here are a few example settings: 

a) Allow anonymous posting (meaning it's not forced anon, and when submitting a post you have a checkbox which says "post anonymously" that you can optionally uncheck if you want to post with your name)

b) force anonymous posting, which is basically what we have now

c) allow/disallow voting. Although anonymous posts shouldn't contribute to a users' CCP they still should be voted on so the subvoat can function properly.  

d) enable thread IDS, which are randomly-generated alphanumeric codes that identify a single user within a thread. Thread ids do not carry over from thread to thread on an anonymous board, but within a single thread they are useful for spotting trolls who attempt to post multiple times with similar comments to sway opinion to their side. Every poster has a thread ID that displays in the upper right of their post, anonymous or not. 

These four options basically cover everything and would make anonymous boards far more usable. 
---

8chan integration is mostly just the ability for users to a) link to 8chan boards like we can link directly to reddit boards and b) an option to post directly to 8chan from the submissions menu while receiving notifications for their posts. 

The proposed markdown for linking to 8chan boards is /8/boardtitle.

**Comment by talons1337** [comment]
The first part of the suggestion is spot on. The all-or-nothing system is quite disagreeable imo. I also don't like /permanent/ anonymisation, but it's the simplest solution. Solutions that would retain anonymity whilst allowing sub owners to turn anon mode off would need to be quite elaborate and a waste of time overall, so I'm not going to suggest it. 

As for the 8chan integration, I'm apathetic towards it. I don't see the point of using it but I don't see the point of stopping others from doing so. 

The only problem I would have is I'm not keen on loading 8chan on this computer and if it becomes used widely, well eh. But that's more of a personal thought. 

Somewhat relevant side note: Voat links to np.reddit.com. I don't think that should be done since according to the reddit admins themselves, np links aren't effective at all.

**Comment by kiwikku** [comment]
Thanks for the comment- i'm glad you agree that the whole all or nothing system needs to change. The easiest way to not have permanent anonymisation would be what i'm suggesting: If you make a sub non-anon, then just leave all the anon posts anonymous and make all future posts named. With mixed anon this wouldn't be a problem. 

8chan integration is mostly just a cooperation thing for me, because when I think anonymous I think 8chan. I feel that our two websites could help each other greatly and form some sort of symbiosis that's completely unlike what 4chan and reddit have. 

I don't think the np links do anything, but it's more just a sign of courtesy.

**Comment by PuttItOut** [comment]
Some of these are planned features or have been partially implemented.
