### ISSUE TITLE
Problem: IP Address hashing doesn't actually accomplish anything

### ISSUE THREAD

**Issue by DanielFlamino** [voat/voat#500]
[Quoting this thread](https://voat.co/v/ideasforvoat/comments/138921/339083/341105#341105)

> There are only ~4 billion (well, 3.7 billion publicly routable) IPv4 addresses. And Voat's IP address hash looks like [this](https://github.com/voat/voat/blob/master/Whoaverse/Whoaverse/Utils/IpHashUtility.cs):
> 
> ```
> public static string CreateHash(string ip)
> {
>     using (SHA512 shaM = new SHA512Managed())
>     {
>         return Convert.ToBase64String(shaM.ComputeHash(Encoding.UTF8.GetBytes(ip)));
>     }
> }
> ```
> 
> I.e. no salt, etc, etc. As such, this is trivial to undo. 4 billion SHA512 hashes on my laptop (!) only takes me about 11 hours with an incredibly naive implementation. So I can literally iterate over all possible IPv4 addresses to find the one that matches. Or, more realistically, load the hashes into a database and iterate over all IPv4 addresses, searching/replacing when I find one that matches.
> 
> About the only way to make this more secure would be to use a pepper - a secure value that is stored separately from the database. But as-is, this isn't adding much of any security.
> 
> This is still a concern with IPv6 addresses, as although the overall space is prohibitively large, it is easy enough to find the segments that are actually used and only iterate over said used sections.

**Comment by pcwiek** [comment]
Yup, that's something that I noticed too.

If you really need to hash the IP and want to use something that's baked into the framework, using something like [Rfc2898DeriveBytes](https://msdn.microsoft.com/en-us/library/system.security.cryptography.rfc2898derivebytes%28v=vs.110%29.aspx) would be the way to go - you can tune the iteration count too.

Or you can use 3rd party C# scrypt implementation.

I have another question though, what happens if two people (with two separate accounts) are using the same machine? Or two or more people that have the same external IP?

**Comment by PuttItOut** [comment]
Closed as code has changed significantly since issue logged.
