### ISSUE TITLE
Dragging anything brings up a massive "share a link" thing.

### ISSUE THREAD

**Issue by talons1337** [voat/voat#534]
Even if you're dragging text. This is extremely annoying when, for example, I want to drag a quote or something into a reply box. I hate having things in my copy/paste clipboard so it's super annoying to have that pop up. 

It's also bugged, because if you hit escape then the "share a link" thing covers the screen permanently. You have to refresh to get rid of it which is incredibly irritating if you already have a reply typed out.

**Comment by Aaron-P** [comment]
This doesn't appear to be 100% fixable due to how the drag-drop api works, but it can be improved a bit.  Using dragstart and dragend to determine if the drag starter within the window will let us get a basic idea if we are dragging something from outside or inside.  If we only want to deal with drag drop events for external things (e.g. websites in other windows) then it should be pretty easy to only show the overlay when the drag is coming from outside.  I'm not sure that's the desired functionality though, I can see use in having links or text urls from in the side (e.g. a comment) be draggable to create a new post out of.  If we want to retain that functionality things get a bit more complex because of cross browser implementation issues but is _possible_ if kind of wonky.  I have only tested this sort of functionality in latest Firefox and Chromium so more testing will probably be needed.

@voat Any input on what the desired functionality is on drag and drop for data outside of the page vs inside the page?

**Comment by PuttItOut** [comment]
Fixed
