### ISSUE TITLE
sub/unsub button highlighting depends on subscription status at page load, doesn't toggle

### ISSUE THREAD

**Issue by mgiuffrida** [voat/voat#568]
If you're subscribed to a subverse, the "unsubscribe" button is dark grey (the other buttons are blue). After clicking to change it to "subscribe" and moving focus elsewhere, the button remains dark grey.

If you're not subscribed when you load the page, the "unsubscribe" button is instead blue, like the "block" button. It remains blue when toggled to "subscribe".

**Comment by h3xx** [comment]
+1 I noticed this too.

Steps to reproduce:

1. Press the **subscribe** button -> button turns into **unsubscribe** button
2. Press the **unsubscribe** button -> button turns into **subscribe** button
3. Refresh the page.

**What happens:** You are subscribed to the subverse.

**What should happen:** Since the last button you presses said **unsubscribe** you should be unsubscribed.

Problem also seen when initial data state is reversed (i.e. you are already subscribed).

**Comment by PuttItOut** [comment]
Fixed
