### ISSUE TITLE
DataBase access layer, repository pattern

### ISSUE THREAD

**Issue by Aaron-P** [voat/voat#585]
One of the biggest (if not the biggest) performance hits right now is the lack of a comprehensive caching layer at the database access layer, so the DB is getting hammered constantly.  The use of something like Redis was mentioned in #446, and is definitely something that should be done, but I would along with that recommend changing the database usage to use the repository pattern so that calls to the database are all at a single layer, instead of in various controllers.  We can then put a cache layer on top of the repositories as a single layer as well.  If there are no major objections I can work towards that, but I want to see if there are any opinions for or against it.

**Comment by bill-long** [comment]
Another benefit of the repository pattern is that you're then set up for dependency injection. Injecting the repository interface would allow you to easily write tests that exercise the controllers and the repository itself.

**Comment by pcwiek** [comment]
@Aaron-P I'd say that repository pattern is definitely *not* necessary if you're using EF - EntityFramework already is a repository and a unit of work at the same time. Wrapping it in another abstraction is hardly ever worth it. It's a different story if you're using a lower-level abstraction (like a micro-ORM)

You can easily do command-query separation via extension methods on appropriate types, which I tried to do in #563 

I'd say the most glaring problem right now is not the DB usage per se (although Redis definitely wouldn't hurt), it's the amount of both trivial and plain *bad* queries. In some places, I easily combined 3+ queries into one that retrieves the same amount of data...

@bill-long Controllers should be thin enough not to require too many tests. EF (both commands and queries) can be tested directly using [Effort](https://www.nuget.org/packages/Effort.EF6), which is - admittedly - a semi-integration test, but it helps with verification that the query at least looks coherent. `DbContext` can be easily injected on its own.

**Comment by Aaron-P** [comment]
Bad queries are certainly a problem, but the _vast_ majority of hits to the site shouldn't be touching the database at all for data retrieval.  If you go to a comment page, how many times are you hitting the database for pure reads?  It's ridiculous for a site with this much traffic.  The main benefit of putting a layer on top of the EF calls is to give a sane place to do DB caches at, otherwise it's going to be happening piecemeal all over the place and be a nightmare to maintain.  If there's a way to do it straight through EF then great.

**Comment by pcwiek** [comment]
@Aaron-P Scala's implicits would come in handy here... But I can see two solutions right off the top of my head:

1. Just pass the Redis interface for those extension methods (queries) that actually need it. Pros: caching is very explicit, cons: it might be *too* explicit with too much repetition everywhere.
2. Add Redis as a property to concrete implementation of `DbContext` as a dependency, where the interface could expose both the core `DbContext` and Redis DB interface as properties - those two would be bundled together, so the cache access could be hidden inside the extension method, yet the access to the property could allow for easy tracing *where* the caching is actually being done

It also depends on the hardware, but if you have beefy enough SQL server so that you can fit your DB (or at least your indexes) in RAM and the rest on SSDs - it should be plenty fast. Otherwise, yeah, Redis seems like a solid choice.

**Comment by cartermp** [comment]
I'm with @Aaron-P on this one.  While I don't find the Repository pattern to be *the* answer, it is a good enough abstraction to allow for a caching layer to be built and maintained easily.  Speaking personally, I really wouldn't want to hunt this kind of stuff down across multiple areas of the application.

**Comment by PuttItOut** [comment]
Hello everyone. First off, thanks for all the support. We are going to need you going forward. I apologize that I haven't been active much on this repo but I will try to change this.

Just a quick update: We understand about all the issues each of you see. We are in the middle of a somewhat larger refactoring when it comes to basic design principles. Unfortunately, our progress has been met with many unforeseeable delays and major requirement changes. We used to be a handful of people working in this code all by ourselves (in fact I haven't even been largely involved in the C# code except for a few component type pieces) so we (Atko and myself) really have a lot of work to do as far as communication and organization.

Anyways, it is clear as day that even the refactoring I have been working on in order to launch the API is too little as no one dreamt Voat would see such rapid growth. We literally thought we had a year timeline to handle double or triple the throughput.

Anyways, I now am rambling. So what we will do once this latest fire is under control is post more info to this community about the direction we want to take things so we can decide as a community how to make Voat the code base we need.

In the meantime we are hoping to get the API fork merged into RealVoat in a week’s time (this may be too optimistic) so that we can start really laying down some enterprise worthy code.

Please feel free to email me and I will try to be more available. Thanks for being so patient with us.

**Comment by Bottswana** [comment]
Thanks for the update, Putitout, I can imagine you two are pretty
overloaded right now. Were all here to help out where we can. Only one
thing, you say we can email you, but what email? :)

**Comment by PuttItOut** [comment]
@Bottswana Oh just PM me on Voat. ;) (Sorry, I'm so tired that this is really funny to me right now)

**Comment by Bottswana** [comment]
@PuttItOut Ehe, I'll remember to do that when I can get back in. You should
take shifts and get some sleep! Haha

**Comment by PuttItOut** [comment]
Closed as code has changed significantly since issue logged. Thanks for the input and suggestions.
