### ISSUE TITLE
Voat is obviously having scaling and performance problems.  How can I help?

### ISSUE THREAD

**Issue by jMyles** [voat/voat#586]
The title says it all.

I see from #585 that you are having some DB access toxicity.  

A good short-term goal is to get a good read-only version to appear in cases where the app is drowning.  Let's throw a little varnish in front and see what happens?

How can I get involved?

**Comment by Bottswana** [comment]
Seconded. I'm just reading through issues looking for anything I can help
on, if theres any direction on what needs looking into specifically I'm all
ears.
-J

**Comment by cartermp** [comment]
This is my person opinion, but a quick look at the project seems to indicate that there's a great deal of work needed here, mainly in stripping out application logic from the controllers.  While that doesn't impact performance per se, the coupling involved would make it exceedingly difficult to get this site to scale well.

#585 is a good start; adding a repository pattern would thin out the controllers significantly and provide some building blocks for adding a caching layer.  Starting on this would be pretty great, but I get the feeling it would need some big approval from the folks who put this together.  Aside from dumping oodles of cash to buy tons of server space, I don't think there's a short-term solution to this.

**Comment by pcwiek** [comment]
From what I noticed during my tinkering with #563 there's *a lot* of places where refactoring of controllers, views and models could (and probably should) be done. For example, all database calls should disappear completely from the views, data models should be mapped to specific view models and fully materialized without any lazy loading, some of the logic (validation, composing the pieces) should be moved to separate services etc.

What I found out was that it's moderately hard to do it right now and not make a monster-PR in the process, especially considering all the DB related changes that are still pending or in the works...

**Comment by ajacques** [comment]
Yeah I just did a quick code review and noticed there were a few things that could be improved too. Maybe we can break this problem down and have different people solve different things.

**Comment by pcwiek** [comment]
I'm waiting for my PR to be merged, but you can check it out feel free to contribute if you want too - I'm pretty sure I didn't refactor everything, at least not yet.

I only cleaned up the queries, but I didn't want to touch the controllers/models/views - that would be too much. Once the queries and commands are there, it should be easier to modify the rest of the architecture.

Note that #563 also includes #488 that introduces xUnit as a testing framework, which I found *very* useful for correctness guarantees when refactoring...

Anyway, feel free to break the problem down further - I know I still have some work to do on my PR.

**Comment by NeilHanlon** [comment]
I think some infrastructure changes/improvements could also help here--caching, geographic load-balancing, etc.

Would love to help out with setting up/configuring some of this stuff for Voat.

**Comment by jMyles** [comment]
Neil - yeah that's what I was volunteering to help with as well.

I'm down to get dirty with the ASP stuff, but I primarily use python these
days.   However, I'm quite sure that we can come up with a good ops
configuration to - at the very least - ensure that a read-only version is
always up.

**Comment by stevenmays** [comment]
I would also like to get involved and help.

**Comment by realcodywburns** [comment]
I guess we are all here for the same reason. I am currently reading through the open issues and seeing where I can help out. From what I have seen, most are hesitant to embrace a aws or azure solution to scalability due to geo-political concerns. It does seem a caching read-only server would help in the mean time to offload some of the heavy traffic but could ruin the user experience

**Comment by galbacarys** [comment]
Question: it's been widely discussed (especially #445) about *why* this project has decided to stick to C#/ASP.net. Having read through that discussion, I think we're in a solid place on our choice of stack, so my next comment is *not* asking for a translation to Rails or some other nonsense.

BUT, why are we continuing to bandage a cancer patient here? Voat was created as a pet project by a couple of students, and they've done a bang-up fucking job with it. It works, it's pretty, and it's got some really cool features I'm excited for. But unfortunately the scale issues we're seeing as of recently are not something that can be fixed with ad-hoc patches and somewhat shoddy organization.

In my mind, a few things need to be done here:

1. an architectural re-think. Realistically, in a project that has the potential to be this huge, the current set up is just not gonna fly. I'm not super familiar with C# or ASP.net, but the codebase is already pretty hard to navigate, and that's without a lot of the planned bells and whistles. We need to make a coordinated effort (say, through the github wiki?) to create a design that will be easier to maintain and improve upon in the future. That's not to say we scrap the project and start over! But we really need to fix many of the big architectural issues now rather than later. Another component of this is adapting the current codebase to a PaaS of some kind so that we can scale cheaply and easily.

2. We need a wiki. Maybe this is my ignorance of ASP showing, but I feel like the codebase is nearly impossible to navigate partially because of the organizational and structural issues and partially because documentation is sparse to non-existent. I'm happy to start building the wiki, but in the end this will need to be coordinated with the aforementioned architectural changes.

I don't mean to sound like an alarmist, I do really just want to see this project succeed. What can I do to help?

**Comment by pcwiek** [comment]
I agree that restructuring is sorely needed. I started doing a little bit of it on my own by separating the queries in the PR, which I mentioned in the previous comment, but there's **a lot** more that needs to be done: a general, sweeping cleanup. What I see happening now is that there is no one coordinating it - and it needs to be coordinated, because there's just too much to be done for everyone to happily hack around and hope for the best.

As far as PaaS options are concerned, once you have the project all cleaned up, putting it on Azure is *really* easy. Microsoft provides Redis on Azure and Azure SQL Database [runs on top of SQL Server](https://azure.microsoft.com/en-gb/documentation/articles/data-management-azure-sql-database-and-sql-server-iaas/) and has full LINQ provider available for EF. Or you can just rent a SQL Server. 

I'm pretty sure Voat guys are swamped with support work, servers etc, but trying to rework the architecture without strong coordination and snappy responses (PR reviewing, comment responses, feature discussions, task management etc) will be very hard.

I have nothing to add re: documentation - I think you're simply right on the money.

**Comment by ajacques** [comment]
Before we start restructuring everything and rewriting things, we really do need to do an architecture design first. If Voat has any hope of scaling up to Reddit-scale traffic, then you can't just haphazardly throw things together and hope it'll work. A design will prevent us from rewriting a bunch of stuff, then finding out it doesn't scale just like the current code base. I've built scalable websites before and you just need to stop and think first.

I've also been reading through the code a little bit to get a handle on it, and it's current state won't scale. Sadly, cause I know the original contributors probably put a lot of effort into it, but I just looked a one web operation that made maybe ~30 database calls.

**Comment by pcwiek** [comment]
@ajacques I'm pretty sure we're in a violent agreement here :) 

And yes, I mentioned it over and over again - when the action calls the database 5 times instead of just 1 while doing queries that are inefficient (for example, `SELECT COUNT(*)` to count all records just to see if the count is > 0 on the client side instead of `SELECT Id WHERE EXISTS` which 'short-circuits'), lazy-loaded database calls and and 'hidden' calls made from the views are the low hanging fruit that have the biggest ROI right now as far as the performance is concerned, IMO. There's a matter of general architecture, too...

And I don't want to bash original team - I remember I made those mistakes once too. Their site became more popular than what their probably hoped for too, which can only count as a success. But at that point, you have to take a good, long look at your code base, because that's the time to fix underlying issues.

**Comment by TNTGav** [comment]
I do agree with majority of sentiments in here, and I think it needs to be done sooner rather than sooner.

Internet users, especially ex reddit users are very fickle things. I think had this kind of scalability been in place during the previous waves of new users, Reddit would have lost a significant chunk of users. There's only so many times they will try an "alternative" site then they will move on to something else. I really want that something else to be Voat. I'm a relative newbie when it comes to ASP.NET and MVC, I've been playing around with it for about 6 months and I'm happy to help where I can.

I'd love it if anyone had an example of a similar, scalable ASP.NET MVC application where business logic is abstracted out to services and the like as I really want to learn. In the mean time I hope the current Voat admins utilise the resources people are offering here to get Voat properly up and running.

I'm sure the original author of the code never had any idea the requirements that would hit the site in the future and it has to be said to have even got to this stage when Voat was essentially a learning project is an amazing achievement.

**Comment by galbacarys** [comment]
@ajacques YES on that architectural design! We should create a Slack or HipChat for everyone and start those discussions ASAP.

@pcwiek I definitely agree on CI, maybe that should be our second step (after improving our unit test suite) in this process. And I didn't know about azure, that's pretty sweet.

I'd be happy to start looking into other ASP.net MVC sites, @TNTGav. I'll post some findings later tonight if I come up with anything.

**Comment by TNTGav** [comment]
@galbacarys Would be much appreciated anything you do find. I have looked, and I have failed.

**Comment by galbacarys** [comment]
Here are some resources I've found:

* [ASP.NET Boilerplate](https://github.com/aspnetboilerplate/aspnetboilerplate)
* [Example app (a little old, but probably not a terrible resource)](https://github.com/iloire/ASP.NET-MVC-ACME-Invoicing--App)
* [A simple blogging app](https://github.com/mikaelm12/Blogger)
*[A "clone" of StackOverflow](https://github.com/szyablitsky/stackoverflow)

It's not an awesome list, but these look like a good start. I'll start studying these over the next few days.

**Comment by ajacques** [comment]
Can we get some input from the core team to know where the current bottlenecks are? That way we can ensure that we solve those issues in a new design or improvement plan. I'm going to take a wild stab and say it's the database falling over, but basically a clear description of "We're encountering too much database contention for the 'SubversesController', or maybe web app CPU usage is too high" would ensure that we can solve those issues.

**Comment by galbacarys** [comment]
As noted above, some of the major problems involve multiple server-side database accesses for simple tasks that could be boiled down to one transaction. There's also some issues with server vs. client side rendering. Once again, I'm not anywhere close to an expert on ASP, but that's my impression so far.

I don't have access to a Windows computer this week, but I will next week, and when I do I might try cloning the repo and doing some profiling. Has anyone else started profiling to see where we're at on resource usage throughout the app?

**Comment by stevenmays** [comment]
I cloned the repo but haven't had a chance to start profiling yet. I will
be doing that this week and post the results.

**Comment by pcwiek** [comment]
@galbacarys Server-side rendering wouldn't be a problem if it wasn't for 'hidden' DB calls that sometimes happen inside the view (!). Those should be refactored...

@stevenmays Please share your findings. 

Even after going through the project manually, for example I know for sure that [this](https://github.com/voat/voat/blob/master/Whoaverse/Whoaverse/Utils/User.cs#L283-L346) can be refactored into [this](https://github.com/pcwiek/voat/blob/ef-changes/Whoaverse/Whoaverse/Queries/User/MiscUserQueries.cs#L71-L86) ([with appropriate view](https://github.com/pcwiek/voat/blob/ef-changes/whoaverse.sql#L1012-L1029)). 

If you do 'Find references', those three methods are always used together, which means all those methods (where each single one, in the worst case, also translates into three separate queries: `SELECT .. FROM ... WHERE EXISTS`,`SELECT .. FROM ... WHERE EXISTS` and `SELECT COUNT(*)`), so 9 queries worst-case in total, can be compacted into just one (!) database trip.

Same comparison can be made here: 

- [current version](https://github.com/voat/voat/blob/master/Whoaverse/Whoaverse/Utils/User.cs#L131-L149), two separate queries retrieving all columns from the table just to compare one column, both executed in controllers one after another, which can be...
- [refactored](https://github.com/pcwiek/voat/blob/ef-changes/Whoaverse/Whoaverse/Queries/User/MiscUserQueries.cs#L21-L43) into one query selecting just one number.

Using async-only queries should make a huge difference too.

**Comment by howez** [comment]
I just fired up the app with ORM Profiler 1.5.  

A logged in user going to a Subverse with a single entry is spinning up 22 connections and 31 SQL Statements.  6 of those connections were not being disposed correctly.

Would be happy to provide detail logs for anyone interested.  

IMHO I would dump EF and opt for something else.  I am using LLBLGEN exclusively for my software projects.  Maybe not a perfect match for this project (it is a commercial product), but it has the ability to prefetch complex graphs in a very efficient way and reduce the number of transactions to the DB.  My current project contains over 400 tables.

Dapper ORM might be another option.  I am using this for the ASP.Net Identity in lieu of EF, mainly for performance reasons and code-first is a sloppy excuse for data modeling.

The profiler does delineate DB time vs .NET time.  The framework performance numbers do not show any need for concern, but I think the sheer number of transactions and connections (as noted multiple times in this thread) is a good place to start.

**Comment by pcwiek** [comment]
@howez Please attach the logs, it will be easier for everyone to see what's going on :)

I still think that throwing away EF completely is throwing out the baby with the bathwater. I do agree that you have to be careful *how* you use it (same goes for any bigger ORM, like NHibernate), but it can be pretty effective. Especially once you restructure the queries and ditch lazy loading...

Any micro-ORM would be a good fit for a hot path in the application, but personally I wouldn't trade strong(er) typing and composable queries for either 'stringly' typing that's prevalent in micro-ORM solutions or reliance on stored procedures (Insight.Database) across the whole project. The core team of the project should make the call though.

**Comment by ajacques** [comment]
I heard MongoDB is web-scale, maybe that'll help us out.
Let's take a look at the logs before we start throwing out any frameworks right now. I mean there's tons of low-hanging fruit here just by consolidating all these queries. I've already been working on cleaning it up. We see so many different single-use methods as opposed to coalescing updates into a single DB operation.
One optimization at a time.

**Comment by PuttItOut** [comment]
Closed as code has changed significantly since issue logged.
