### ISSUE TITLE
asp.net 5 / mvc 6

### ISSUE THREAD

**Issue by celluj34** [voat/voat#590]
Apologies if this had already been discussed, but I wanted to know if there were plans to upgrade to asp.net 5 and mvc 6. They are still in beta now, but perfectly usable. The only problem i have with my personal projects is hosting .net 4.6.

**Comment by ryanelian** [comment]
-1

Beta is outdated and nightly is unstable. Core CLR doesn't work with most library. Current voat website uses EF6 which requires dnx451 instead of core CLR which negates the reason to migrate to ASP.NET 5 (speed). EF7 is far from complete. Dapper build for core CLR is in beta form, not suitable for production.

**Comment by Romoku** [comment]
Upgrading from MVC 5 to MVC 6 will require a bit of work. All the frontend nuget dependencies (bootstrap, jquery, etc...) and asset minification must be moved to Bower and Gulp. EF is remaining largely the same.

**Comment by celluj34** [comment]
Maybe now would be a good time to pseudo-design with the new versions in
mind? Also in that way new contributors would have an easier time with a
clear design in mind. Something like:

Voat.Web: contains controllers and all front end libs
Voat.Application: contains all business logic, viewmodels, and is the meat
of the project
Voat.Domain (or database or DAL or whatever): contains all database
interaction code, whether it's repository style or otherwise
Voat.Infrastructure (or Services): container all interaction with outside
services, email, sms, etc
Voat.UnitTest: unit tests
Voat.IntegrationTest: integration tests

And maybe a small wiki of how they would work together and who references
what.

**Comment by Romoku** [comment]
+1 to more documentation. I use [ReadTheDocs](https://readthedocs.org/) with a separate repository (e.g. Voat/Docs).

The new ASP.NET structure is relatively straightforward. The docs are available at [docs.asp.net](http://docs.asp.net/en/latest/). These are versioned using readthedocs under [aspnet/docs](https://github.com/aspnet/Docs).

MVC 6 uses the following conventions:

- wwwroot -- This is where all client side code lives (html/css/js)
- wwwroot/lib -- Bower libraries are kept here
- Controllers -- Controller location remain the same from MVC 5
- Models -- Viewmodel location remains the same from MVC 5
- Views -- Razor view location remains the same from MVC 5
- bower.json -- bower config is located at the root of the project
- package.json -- node.js config is located at the root of the project
- gulpfile.js/gruntfile.js -- Task runner config is located at the root of the project
- Startup.cs -- All bootstrapping and setup code (DI/Database/API) happens here. Global.asax is gone.
- config.json -- Web.config is no longer required and a new json based configuration is available.
- project.json -- Stores all the project metadata, dependencies, and commands for DNX. Replaces nuget packages.config.

Additionally csproj and sln files are gone. Visual Studio will generate an xproj but that is used for its housekeeping.

My proposed structure is:

* Voat.Core: Reusable library with common code
* Voat.Domain: Library with all the domain models.
* Voat.Database: Keeps the DAL/DB Models and will Setup/Migrate the database
* Voat.Web: Frontend project using described MVC 6 conventions
* Voat.API: Web API for Mobile and Desktop clients
* Voat.Mobile: Contains all the data structures for the API

**Comment by celluj34** [comment]
-1 for Voat.API. Web api and mvc controllers are now unified. No need for
separation. In fact, I think the site and mobile apps should use the exact
same api calls to elimination fracturing of logic.

**Comment by Romoku** [comment]
Well designing an API and designing a website are different domains. Controllers are now unified, but they need to return content in different formats depending on the client.

The same API calls could be made if Voat were converted to something like an SPA, but I have not tried splitting content in controllers.

**Comment by celluj34** [comment]
The point I was trying to make is that they don't have to return them in
different formats. I'm of the opinion that there should be one action to
get the home page, for example, and every customer should decide what they
do with the data.

**Comment by olso** [comment]
I think you lost out on huge coder base by going with asp.net

**Comment by Romoku** [comment]
@olso I don't see how that is relevant to the discussion.

**Comment by kowsheek** [comment]
:+1: 

MVC 6 is awesome, I've been using it on our (live) product since beta3. While RTM is still somewhat down the road, if the switch is the take place (which it should), it should happen asap.

Agreed with @Romoku's analysis too. And yes there will be the need for API controllers vs MVC controllers though, the implementation has been unified.

For example,

Api/InboxPrivateMessages should return you a json/xml representation of that resource. Whereas Web/InboxPrivateMessages would return a CSHTML view, which in turn can call the API method. Or, both the Api method and the MVC method call into the data layer.

**Comment by TNTGav** [comment]
Last time I check you couldn't even do any scaffolding in 2015 RC. Is that still the case?

**Comment by Romoku** [comment]
@TNTGav Visual Studio has templates. The new AspNet does not require Visual Studio. You can now use Yeoman to scaffold with [generator-aspnet](https://www.npmjs.com/package/generator-aspnet).

**Comment by celluj34** [comment]
@kowsheek @Romoku yeah, what i want to avoid is duplicating logic. So if the Web calls the API layer for data, then that's perfect. Just have the Web be a shell around calls to the API is fine with me. Or, if both call into an (what my work calls) orchestration layer, where all the logic resides, that's fine too.

**Comment by Romoku** [comment]
Ideally controllers should not have business logic.

**Comment by thestamp** [comment]
I concur, the logic should be in the BLL, with the API and Web layers
calling it.

Are we planning to follow DDD?

**Comment by danieldafoe** [comment]
While you guys are discussing ASP.NET 5, etc, I have a question. Is it possible for me to contribute to voat on OS X?

Yesterday I installed the OmniSharp package for Atom as well as DNX/DNVM but when I open a C# file in Atom it only seems to load *some* of the dependencies. Any ideas? (Mono installation is supported as well.)

**Comment by Romoku** [comment]
Voat is using ASP.NET 4 + MVC 5. Kestrel does not support them AFAIK. However, you should still be able to use OmniSharp to write code and FTP deploy to remote IIS.

**Comment by 436wtw3ry546** [comment]
:+1: It should be done as soon as possible

**Comment by kowsheek** [comment]
@TNTGav VS has much better support now. With RTM is coming out in a few weeks so it'll have full support.

@danieldafoe You can follow the method @Romoku suggests until we move to ASP.Net 5.

**Comment by kowsheek** [comment]
For moving to ASP.Net 5, I'd recommend the following steps:

Phase 1:
1. Rework the existing controllers to use services that should be written with minimum dependencies on ASP.Net/MVC/WebApi. I believe #593 is on the right track with this move. This should be the Voat.Core, Voat.Domain, Voat.Database, Voat.Mobile libraries. The idea should be to preemptively introduce the service model of ASP.Net 5.

2. Move static asset management to Gulp (or Grunt, though Gulp is the default since beta4) so we can prepare for the change of build system.

Phase 2:
3. Upgrade to ASP.Net 5 as just the Voat.Web project.

4. Refactor out API methods and split it into Voat.API.

5. Update Voat.Web frontend Javascript layer to use Voat.API methods.

Item 1 should make the process of upgrading much simpler, so I think that's what we should focus on getting done. I'm hoping to make some PRs soon :)

Thoughts?

**Comment by celluj34** [comment]
One thing I want to throw out is that everything except controllers
implements an interface, for testability. That way both front-end and
back-end tests can be added as we go without a major refactor at any point.

**Comment by kowsheek** [comment]
@celluj34 This is a discussion for #593 I'd say. But it doesn't make sense to have a blanket rule to create and implement interfaces, it'd depend on the case. But yes that would be the route we take, since we will be implementing it middleware style.

**Comment by celluj34** [comment]
ok, will comment there also.

Joseph Cellucci
Software Developer
ITA Group
celluj34@gmail.com

**Comment by Romoku** [comment]
@kowsheek +1 That is a pretty good upgrade path. Additionally many conventions have changed like middleware and dependency injection. The codebase will be in better shape for a migration once all the framework logic (EF/Authentication/Authorization) is decoupled from the business logic.

Additionally reworks will be needed for frontend since the development story has changed with ASP.NET 5.

I am working on my own fork [Romoku/Voat](https://github.com/Romoku/voat) and I am starting with improving the build system to make deployments and testing simplier.

**Comment by danieldafoe** [comment]
@kowsheek Thanks for the info. I'll try that out. I've been having trouble with the OmniSharp Atom plugin pulling in the dependencies, though. I'll have to give it another whirl this evening.

**Comment by PuttItOut** [comment]
Closed as code has changed significantly since issue logged.
