### ISSUE TITLE
Forgot password feature

### ISSUE THREAD

**Issue by voat** [voat/voat#6]
Users which chose to link an email address to their account should be able to use a "forgot password" feature in case they forgot their password. The feature would send a one-time link to a "change password" page and allow the user to change their password.

**Comment by s0r00t** [comment]
Is there any updates about this? I've just made an account, set up my email but LastPass lost my generated pass...

**Comment by KoenDG** [comment]
I'm commenting here to highlight this issue. I once tried setting up a VS environment to do this myself, but it's been just way too long since I worked in .NET

I don't know any of these libraries, I can't find any good instructions on how to set em all up, how to link everything, etc...

And believe me, I tried. I just couldn't find it. An instruction video would be nice. On how to set up a dev environment to the point where you can say: "and now you can write any code and commit it and it should fit in"

**Comment by voat** [comment]
This is now implemented.
