### ISSUE TITLE
Submitting a URL with a double-# in it doesn't work

### ISSUE THREAD

**Issue by psy-q** [voat/voat#666]
I wanted to post the following URL:

    http://www.gog.com/games##sort=bestselling&system=lin_mint,lin_ubuntu&price=discounted&page=1

Which seems valid, but it looks like Voat doesn't like the double-# and claims it's not valid.

**Comment by jksg** [comment]
Voat is right — it’s technically not a valid URI.

`#` denotes the *fragment* identifier of a URI, and within the fragment id the character `#` itself is not allowed. A URI can also only have one fragment identifier; therefore, logically a URI can have only one (unescaped) `#`. See [RFC-3986](https://www.ietf.org/rfc/rfc3986.txt) section 3.5 on fragments, as well as appendix A for the definition of pchar.

Why GOG chose to use `##` instead of the standard `?` for what is otherwise a conventional query string is baffling.

**Comment by psy-q** [comment]
Ah, alright! Should we poke the GOG people about this? I can't seem to make a working URL without using ## :(

**Comment by craigmaslowski** [comment]
Removing one of the # seems to work. When I do that, it get's rewritten to #/ as seen below. 

http://www.gog.com/games#/sort=bestselling&system=lin_mint,lin_ubuntu&price=discounted&page=1#sort=bestselling&system=lin_mint,lin_ubuntu&price=discounted&page=1

**Comment by psy-q** [comment]
Yes, and half the query string gets repeated thrice. Odd. But not a Voat problem then, so closing :)
