### ISSUE TITLE
Improve datetime display for humans and machines

### ISSUE THREAD

**Issue by jusk64** [voat/voat#687]

**Comment by talons1337** [comment]
I really hate ISO 8601 dates when given to humans because they're inconvenient to read. I don't get why there's so much "ISO 8601 this! ISO 8601 that!" as is common basically anywhere that you find nerds on the internet. 

Anyway I think allowing the user to manually set their date-time layout preferences and timezone would be best. I would even go as far as saying they should have a say in choosing separators. I like to use slashes for example and dots in dates are jarring to me.

**Comment by jksg** [comment]
Convenience is subjective — I find it far more convenient to read than any other numerical date format. As you can see in my suggestion, I refrained from showing any ISO 8601 dates to humans despite my personal preference.

Of course letting the user choose would be best for the user, but feature requests aren’t always best for the developer :P For a quick fix I believe we can start by using [`ToString("o")`](https://msdn.microsoft.com/en-us/library/az4se3k1(v=vs.110).aspx#Roundtrip) on the machine-readable dates.
