### ISSUE TITLE
This device cannot be used to create a Voat account

### ISSUE THREAD

**Issue by conzorz** [voat/voat#775]
Even on Tor! You rascals. Let me in :(

**Comment by junkblocker** [comment]
Looking at the code, they are saving accounts created per IP address. If those exceed a certain number you see this message. Since there are not too many Tor exits, and other brilliant minds have had the same idea as you, you'll keep seeing this until you find an unused one.

Sadly, this rules out creating accounts from behind big company firewalls/NATs too.

**Comment by voat** [comment]
This should no longer be an issue.
