### ISSUE TITLE
Issue while creating title with Turkish characters

### ISSUE THREAD

**Issue by chufy** [voat/voat#903]
Hello, I've successfully installed Voat on windows server but when I trying to create a title contains "Turkish" characters it gives an error and deletes "ŞŞ,şş,ğğ,ıı,İİ" characters on the title.

It occurs on repository when process title text. Can anyone help me with that? Thank you.
"Voat has strip searched your title and removed it's unicode. Please verify you approve of what you see."
![qfwf](https://cloud.githubusercontent.com/assets/20624397/26741577/95c144d8-47e2-11e7-9ebf-f98da6ebea1d.PNG)

**Comment by DanielFlamino** [comment]
See #330, #411, #571 and #664.

**Comment by chufy** [comment]
Thank you, Daniel, but I can't find the solution. Found a commit on a topic that you have sent but it seems outdated. Can you show me a way to solve this?

**Comment by DanielFlamino** [comment]
I showed those issues because Voat simply doesn't allow those characters. No character with a code higher than 255 is allowed (so almost all of Unicode is out).

Anyway, Voat [checks if there's any character with a code higher than 255](https://github.com/voat/voat/blob/d98e8a02167a5ba4a5b1432c0ebefc7ffdadeb02/Voat/Voat.Business/Utilities/Submissions.cs#L93-L98). If there are any characters like that (which Turkish characters would fall into), it adds the error message to the response and [removes all of those "forbidden" characters](https://github.com/voat/voat/blob/d98e8a02167a5ba4a5b1432c0ebefc7ffdadeb02/Voat/Voat.Business/Utilities/Submissions.cs#L100-L104). So, changing the ContainsUnicode method to just return false should do the trick. It would, however, allow any character that is part of Unicode to be accepted, which you may want to or not (Voat doesn't because of people putting emojis in titles IIRC).

**Comment by chufy** [comment]
So if we return ContainsUnicode to false, can we create an exception for emojis in the title?
